#!/usr/bin/env python3
"""
Seed 200+ more calculators: European brands, Soviet/Eastern bloc,
Casio scientific expansion, Sharp, Canon, Olivetti, Rockwell,
National Semiconductor, Compucorp, Wang, Nixdorf, Triumph-Adler, Sanyo, Toshiba, Citizen.

Run inside the backend container:
  docker compose exec backend python /app/../scripts/seed_big.py
Or locally with DB access:
  DATABASE_URL=... python scripts/seed_big.py
"""
import asyncio
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'backend'))

from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker
from sqlalchemy import select, and_

DATABASE_URL = os.environ.get(
    'DATABASE_URL',
    'postgresql+asyncpg://curiocalc:changeme@localhost:5432/curiocalc'
)

CALCULATORS = [
    # ── Casio scientific expansion ──────────────────────────────────────
    {"make":"Casio","model":"fx-115ES Plus","year_introduced":2008,"calc_type":"scientific","display_type":"LCD","power_source":"solar+battery","num_keys":47,"country_of_origin":"Japan","description":"Natural Textbook Display showing expressions as they appear in textbooks. One of the most capable non-graphing scientific calculators ever made, with 280+ functions.","tags":["natural-display","solar","textbook-display","popular"],"rarity_score":2.0,"weirdness_score":1.5},
    {"make":"Casio","model":"fx-991EX","year_introduced":2015,"calc_type":"scientific","display_type":"LCD","power_source":"solar+battery","num_keys":47,"country_of_origin":"Japan","description":"Classwiz series with high-resolution LCD. Can display spreadsheet-style tables and has a QR code function to send results to a smartphone.","tags":["classwiz","qr-code","natural-display","solar"],"rarity_score":2.0,"weirdness_score":3.0},
    {"make":"Casio","model":"fx-7000G","year_introduced":1985,"calc_type":"graphing","display_type":"LCD","power_source":"battery","num_keys":66,"country_of_origin":"Japan","description":"World's first graphing calculator. The fx-7000G could graph up to three functions simultaneously on its 96×64 dot matrix display.","tags":["first","graphing","historic","milestone"],"rarity_score":7.5,"weirdness_score":5.0},
    {"make":"Casio","model":"fx-9860GII","year_introduced":2008,"calc_type":"graphing","display_type":"LCD","power_source":"battery","num_keys":60,"country_of_origin":"Japan","description":"High-resolution graphing calculator with a natural display. Popular in Europe and Asia as an alternative to TI graphing calculators.","tags":["graphing","natural-display","exam-approved"],"rarity_score":3.0,"weirdness_score":2.0},
    {"make":"Casio","model":"Algebra FX 2.0","year_introduced":1999,"calc_type":"graphing","display_type":"LCD","power_source":"battery","num_keys":78,"country_of_origin":"Japan","description":"Featured a built-in CAS (Computer Algebra System) — a rare feature at this price point. Discontinued relatively quickly, making it sought after by collectors.","tags":["cas","graphing","rare","discontinued"],"rarity_score":7.0,"weirdness_score":5.0},
    {"make":"Casio","model":"ClassPad 300","year_introduced":2003,"calc_type":"graphing","display_type":"LCD","power_source":"battery","country_of_origin":"Japan","description":"Casio's touchscreen graphing calculator with a stylus. Ran a full CAS and had an icon-based interface. A bold departure from button-only calculators.","tags":["touchscreen","stylus","cas","graphing"],"rarity_score":6.5,"weirdness_score":7.0},
    {"make":"Casio","model":"fx-3600P","year_introduced":1981,"calc_type":"programmable","display_type":"LCD","power_source":"battery","num_keys":38,"country_of_origin":"Japan","description":"Early programmable scientific calculator with 38 program steps. A popular choice for students and engineers in the early 1980s.","tags":["programmable","vintage","scientific"],"rarity_score":5.0,"weirdness_score":3.0},
    {"make":"Casio","model":"MG-880","year_introduced":1981,"calc_type":"novelty","display_type":"LED","power_source":"battery","country_of_origin":"Japan","description":"Calculator combined with a mini game console featuring Space Invaders-style games. One of the earliest 'game calculators' that blurred the line between toy and tool.","fun_facts":"The MG-880 predates the Game Boy by 8 years and was an early example of convergence devices.","tags":["game","novelty","vintage","collectible"],"rarity_score":8.5,"weirdness_score":9.5},
    {"make":"Casio","model":"FX-702P","year_introduced":1981,"calc_type":"programmable","display_type":"LCD","power_source":"battery","country_of_origin":"Japan","description":"Pocket computer with BASIC programming capability. Could accept printed circuit card expansions and connect to a thermal printer/cassette unit.","tags":["basic","pocket-computer","programmable","expandable"],"rarity_score":6.5,"weirdness_score":6.0},
    {"make":"Casio","model":"fx-CG50","year_introduced":2017,"calc_type":"graphing","display_type":"LCD","power_source":"battery","num_keys":62,"country_of_origin":"Japan","description":"Color graphing calculator with a natural display. Features 3D graphing and Python programming support added via firmware update.","tags":["color","3d-graphing","python","modern"],"rarity_score":3.0,"weirdness_score":2.5},

    # ── Sharp scientific expansion ───────────────────────────────────────
    {"make":"Sharp","model":"EL-5500III","year_introduced":1984,"calc_type":"programmable","display_type":"LCD","power_source":"battery","num_keys":50,"country_of_origin":"Japan","description":"Pocket computer programmable in BASIC. Had a full QWERTY-like keyboard and could store up to 1K of program memory.","tags":["basic","programmable","pocket-computer","qwerty"],"rarity_score":6.0,"weirdness_score":5.5},
    {"make":"Sharp","model":"EL-9300","year_introduced":1992,"calc_type":"graphing","display_type":"LCD","power_source":"battery","country_of_origin":"Japan","description":"Sharp's graphing calculator featuring a 64×96 pixel display. Competed with the TI-81 and Casio fx-7700G in the early graphing calculator market.","tags":["graphing","vintage","scientific"],"rarity_score":6.0,"weirdness_score":3.5},
    {"make":"Sharp","model":"EL-506W","year_introduced":2000,"calc_type":"scientific","display_type":"LCD","power_source":"solar+battery","num_keys":51,"country_of_origin":"Japan","description":"Dual-power scientific calculator with WriteView — Sharp's natural textbook display system. Competed directly with Casio's natural display calculators.","tags":["writeview","natural-display","solar"],"rarity_score":3.0,"weirdness_score":2.0},
    {"make":"Sharp","model":"Compet 20","year_introduced":1964,"calc_type":"other","display_type":"nixie","power_source":"AC","country_of_origin":"Japan","description":"One of Sharp's earliest electronic calculators, using nixie tube displays and discrete transistor circuitry. A landmark in Japanese electronics history.","tags":["nixie","vintage","historic","desktop","transistor"],"rarity_score":9.5,"weirdness_score":8.0},
    {"make":"Sharp","model":"EL-8048","year_introduced":1977,"calc_type":"scientific","display_type":"LED","power_source":"battery","num_keys":41,"country_of_origin":"Japan","description":"Early LED scientific calculator. Features a distinctive slide-rule-style case design that flips open to reveal the keyboard.","tags":["led","vintage","clamshell","scientific"],"rarity_score":7.0,"weirdness_score":6.5},

    # ── HP expansion ─────────────────────────────────────────────────────
    {"make":"HP","model":"HP-01","year_introduced":1977,"calc_type":"other","display_type":"LED","power_source":"battery","country_of_origin":"USA","description":"A calculator wristwatch — arguably the most ambitious consumer electronic of its era. Could perform calculations, display time, date, and alarm functions. Required a special stylus to operate the tiny keys.","fun_facts":"The HP-01 sold for $795 in 1977, equivalent to about $3,500 today. HP's own engineers called it 'a solution looking for a problem.'","tags":["watch","wristwatch","led","historic","luxury","weird"],"rarity_score":9.8,"weirdness_score":9.8},
    {"make":"HP","model":"HP-35","year_introduced":1972,"calc_type":"scientific","display_type":"LED","power_source":"battery","num_keys":35,"country_of_origin":"USA","description":"World's first handheld scientific calculator. Named for its 35 keys. Rendered the slide rule obsolete overnight and sold for $395.","fun_facts":"HP engineers bet Bill Hewlett $10,000 it couldn't be done. Hewlett won.","tags":["first","historic","rpn","led","milestone","slide-rule-killer"],"rarity_score":9.0,"weirdness_score":6.0},
    {"make":"HP","model":"HP-65","year_introduced":1974,"calc_type":"programmable","display_type":"LED","power_source":"battery","num_keys":35,"country_of_origin":"USA","description":"World's first handheld programmable calculator. Programs stored on magnetic cards. NASA used it as a backup computer on the 1975 Apollo-Soyuz mission.","fun_facts":"Flew to space on Apollo-Soyuz as an emergency navigation backup.","tags":["programmable","magnetic-card","rpn","nasa","historic","first"],"rarity_score":9.5,"weirdness_score":7.5},
    {"make":"HP","model":"HP-67","year_introduced":1976,"calc_type":"programmable","display_type":"LED","power_source":"battery","num_keys":35,"country_of_origin":"USA","description":"Successor to the HP-65 with 224 programmable steps and improved magnetic card reader. The standard tool for engineers and scientists through the late 1970s.","tags":["programmable","magnetic-card","rpn","engineering"],"rarity_score":8.0,"weirdness_score":5.0},
    {"make":"HP","model":"HP-41C","year_introduced":1979,"calc_type":"programmable","display_type":"LCD","power_source":"battery","num_keys":63,"country_of_origin":"USA","description":"Revolutionary expandable calculator with alphanumeric display. Had a full module system with ROMs for surveying, navigation, medicine, and more. Used by NASA astronauts on Space Shuttle missions.","fun_facts":"NASA certified the HP-41C for use on Space Shuttle missions. There's even a module that let it interface with the Space Shuttle's navigation system.","tags":["expandable","modules","rpn","alphanumeric","nasa","space-shuttle"],"rarity_score":7.5,"weirdness_score":7.0},
    {"make":"HP","model":"HP-16C","year_introduced":1982,"calc_type":"programmable","display_type":"LCD","power_source":"battery","num_keys":44,"country_of_origin":"USA","description":"Computer scientist's calculator. Designed specifically for programmers with hex/octal/binary display modes, bit manipulation functions, and floating-point to integer conversions. Highly sought after by vintage computing enthusiasts.","tags":["rpn","programmer","hex","binary","computer-scientist","collectible"],"rarity_score":8.5,"weirdness_score":6.0},
    {"make":"HP","model":"HP-28C","year_introduced":1987,"calc_type":"graphing","display_type":"LCD","power_source":"battery","country_of_origin":"USA","description":"HP's first graphing calculator and first with a CAS (Computer Algebra System). Clamshell design with a full equation library. Essentially a pocket computer.","tags":["cas","graphing","rpn","clamshell","first-hp-graphing"],"rarity_score":7.5,"weirdness_score":7.0},
    {"make":"HP","model":"HP-48GX","year_introduced":1993,"calc_type":"graphing","display_type":"LCD","power_source":"battery","num_keys":49,"country_of_origin":"USA","description":"The pinnacle of HP's RPN graphing calculators. Expandable via RAM and ROM cards, it had a full CAS, symbolic algebra, and could run custom programs. Still has an active community writing software for it.","tags":["rpn","cas","graphing","expandable","classic","community"],"rarity_score":6.5,"weirdness_score":5.5},
    {"make":"HP","model":"HP-49G","year_introduced":1999,"calc_type":"graphing","display_type":"LCD","power_source":"battery","num_keys":49,"country_of_origin":"USA","description":"First HP graphing calculator with a USB port. Ran HP's User RPL and System RPL languages. Featured both RPN and algebraic input modes.","tags":["rpn","cas","graphing","usb","dual-mode"],"rarity_score":5.5,"weirdness_score":4.0},
    {"make":"HP","model":"HP-12C Platinum","year_introduced":2003,"calc_type":"financial","display_type":"LCD","power_source":"battery","num_keys":43,"country_of_origin":"USA","description":"Updated version of the legendary HP-12C with faster processor and added algebraic mode. Still uses the same RPN layout that finance professionals have loved since 1981.","tags":["rpn","financial","business","professional","long-lived"],"rarity_score":4.0,"weirdness_score":2.5},

    # ── Texas Instruments expansion ──────────────────────────────────────
    {"make":"TI","model":"TI-30X IIS","year_introduced":1999,"calc_type":"scientific","display_type":"LCD","power_source":"solar+battery","num_keys":42,"country_of_origin":"USA","description":"Two-line scientific calculator with solar+battery power. One of the best-selling scientific calculators of all time, found in millions of American classrooms.","tags":["solar","two-line","popular","classroom"],"rarity_score":1.5,"weirdness_score":1.0},
    {"make":"TI","model":"TI-73","year_introduced":1998,"calc_type":"graphing","display_type":"LCD","power_source":"battery","num_keys":40,"country_of_origin":"USA","description":"Designed for middle school students, the TI-73 had a friendlier interface with larger fonts and built-in activities. Could connect to CBL/CBR lab equipment.","tags":["graphing","middle-school","educational","cbl"],"rarity_score":4.0,"weirdness_score":2.5},
    {"make":"TI","model":"TI-80","year_introduced":1995,"calc_type":"graphing","display_type":"LCD","power_source":"battery","num_keys":40,"country_of_origin":"USA","description":"Entry-level graphing calculator replacing the TI-81. Had a split-screen capability and could link to the TI-82 and TI-83 but with more limited memory.","tags":["graphing","entry-level","classroom","link"],"rarity_score":4.5,"weirdness_score":2.0},
    {"make":"TI","model":"TI-Nspire CX CAS","year_introduced":2011,"calc_type":"graphing","display_type":"LCD","power_source":"battery","num_keys":55,"country_of_origin":"USA","description":"Full-color graphing calculator with a computer algebra system. Features a clickpad interface and can display 3D graphs. The CAS version is banned from some standardized tests.","tags":["cas","color","graphing","clickpad","3d"],"rarity_score":3.5,"weirdness_score":3.0},
    {"make":"TI","model":"TI-92","year_introduced":1995,"calc_type":"graphing","display_type":"LCD","power_source":"battery","num_keys":70,"country_of_origin":"USA","description":"QWERTY keyboard graphing calculator with a full CAS. Its size (too big to fit in a pocket) and full keyboard got it banned from standardized tests, limiting its market. Features Derive-based symbolic math engine.","fun_facts":"The TI-92 was banned from SAT and ACT tests because of its QWERTY keyboard — regulators feared it was too much like a computer.","tags":["qwerty","cas","graphing","banned","large","derive"],"rarity_score":6.5,"weirdness_score":7.5},
    {"make":"TI","model":"TI-Voyage 200","year_introduced":2002,"calc_type":"graphing","display_type":"LCD","power_source":"battery","num_keys":70,"country_of_origin":"USA","description":"Successor to the TI-92 Plus with larger memory and expanded Flash applications. Like its predecessor, banned from standardized tests. Popular among engineering students in Europe.","tags":["qwerty","cas","graphing","large","banned"],"rarity_score":6.0,"weirdness_score":6.5},
    {"make":"TI","model":"TI-5045 SV","year_introduced":1985,"calc_type":"printing","display_type":"LCD","power_source":"AC","country_of_origin":"USA","description":"Desktop printing calculator with a two-color ribbon printer. Could perform tax and grand total calculations. Common in accounting offices throughout the 1980s and 90s.","tags":["printing","desktop","accounting","two-color"],"rarity_score":4.0,"weirdness_score":2.0},
    {"make":"TI","model":"TI-30 Galaxy","year_introduced":1983,"calc_type":"scientific","display_type":"LCD","power_source":"solar","num_keys":32,"country_of_origin":"Taiwan","description":"Solar-only scientific calculator in a distinctive space-age case. One of TI's early solar calculators with bright yellow accent keys.","tags":["solar","vintage","scientific","colorful"],"rarity_score":6.0,"weirdness_score":4.5},
    {"make":"TI","model":"Little Professor","year_introduced":1976,"calc_type":"novelty","display_type":"LED","power_source":"battery","country_of_origin":"USA","description":"Educational calculator designed for children that reversed the usual operation — it showed math problems and children had to type in the answer. Became hugely popular as an educational toy.","fun_facts":"The Little Professor was the first mass-market educational calculator for children and sold over a million units in its first year.","tags":["educational","children","toy","led","novelty"],"rarity_score":6.0,"weirdness_score":7.0},
    {"make":"TI","model":"Speak & Math","year_introduced":1980,"calc_type":"novelty","display_type":"other","power_source":"battery","country_of_origin":"USA","description":"Speaking educational calculator that literally talks to children. Uses TI's own speech synthesis chip to announce math problems and feedback.","fun_facts":"Speak & Math used TI's pioneering LPC speech synthesis technology — the same tech that powered the Speak & Spell.","tags":["speech","educational","toy","novelty","talking"],"rarity_score":6.5,"weirdness_score":9.0},

    # ── Soviet / Eastern Bloc ────────────────────────────────────────────
    {"make":"Elektronika","model":"MK-52","year_introduced":1985,"calc_type":"programmable","display_type":"LED","power_source":"battery","num_keys":43,"country_of_origin":"USSR","description":"Soviet programmable calculator that flew to space on the Soyuz TM-7 mission as an emergency backup navigation computer. Had an EEPROM expansion slot for non-volatile program storage — a first for Soviet calculators.","fun_facts":"An MK-52 reportedly saved the lives of cosmonauts when the main computer failed during reentry of Soyuz TM-7 in 1989.","tags":["soviet","programmable","space","ussr","historic","soyuz"],"rarity_score":9.0,"weirdness_score":8.5},
    {"make":"Elektronika","model":"MK-61","year_introduced":1983,"calc_type":"programmable","display_type":"LED","power_source":"battery","num_keys":39,"country_of_origin":"USSR","description":"Soviet reverse polish notation programmable calculator. Reverse-engineered from the HP-35/HP-65 but with unique Soviet modifications. Had 105 programmable steps.","tags":["soviet","rpn","programmable","ussr","hp-clone"],"rarity_score":7.5,"weirdness_score":7.0},
    {"make":"Elektronika","model":"B3-34","year_introduced":1980,"calc_type":"programmable","display_type":"LED","power_source":"battery","num_keys":21,"country_of_origin":"USSR","description":"Popular Soviet programmable calculator with 98 program steps. Had a dedicated user community that published books of programs for engineering and scientific applications.","tags":["soviet","programmable","ussr","popular"],"rarity_score":7.0,"weirdness_score":6.0},
    {"make":"Elektronika","model":"MK-85","year_introduced":1986,"calc_type":"programmable","display_type":"LCD","power_source":"battery","country_of_origin":"USSR","description":"Soviet pocket computer programmable in BASIC. One of the few Soviet calculators to use an LCD display and support a high-level language.","tags":["soviet","basic","pocket-computer","ussr","lcd"],"rarity_score":8.0,"weirdness_score":7.0},
    {"make":"Elektronika","model":"MK-90","year_introduced":1986,"calc_type":"programmable","display_type":"LCD","power_source":"battery","country_of_origin":"USSR","description":"Soviet graphical pocket computer. Featured a 120×64 pixel graphics-capable LCD — remarkable for a Soviet device. Could display graphs and basic graphics under BASIC control.","fun_facts":"The MK-90 was so advanced for Soviet technology that production was extremely limited, making it exceptionally rare today.","tags":["soviet","graphical","ussr","rare","lcd","pocket-computer"],"rarity_score":9.5,"weirdness_score":8.5},
    {"make":"Robotron","model":"SR1","year_introduced":1975,"calc_type":"scientific","display_type":"LED","power_source":"battery","country_of_origin":"East Germany","description":"East German scientific calculator produced by Robotron, the state computer manufacturer. Used West German-designed LED displays smuggled or reverse-engineered.","tags":["east-german","cold-war","scientific","led","ddr"],"rarity_score":9.0,"weirdness_score":7.5},
    {"make":"Facit","model":"ESA-01","year_introduced":1971,"calc_type":"scientific","display_type":"nixie","power_source":"AC","country_of_origin":"Sweden","description":"Swedish electronic calculator from Facit, a company that had dominated the mechanical calculator market. The shift to electronics came too late — Facit went bankrupt just months after releasing this model.","fun_facts":"Facit's parent company ignored an internal report that showed electronic calculators would make mechanical ones obsolete. They went bankrupt in 1973 with 10,000 employees.","tags":["swedish","nixie","historic","bankruptcy","tragic"],"rarity_score":9.5,"weirdness_score":8.0},
    {"make":"Iskra","model":"123","year_introduced":1974,"calc_type":"other","display_type":"nixie","power_source":"AC","country_of_origin":"Yugoslavia","description":"Yugoslavian desktop calculator with nixie tube display. The Iskra factory in Ljubljana produced some of the few electronic calculators manufactured in socialist Yugoslavia.","tags":["yugoslav","nixie","desktop","socialist","rare"],"rarity_score":9.5,"weirdness_score":8.0},

    # ── European brands ──────────────────────────────────────────────────
    {"make":"Olivetti","model":"Divisumma 24","year_introduced":1956,"calc_type":"other","display_type":"other","power_source":"AC","country_of_origin":"Italy","description":"Electromechanical printing calculator designed by Marcello Nizzoli — considered one of the most beautiful office machines ever made. Won the Compasso d'Oro design award. Now in MoMA's permanent collection.","fun_facts":"The Divisumma 24 is in the permanent collection of New York's Museum of Modern Art. Its designer Nizzoli also designed the Lettera 22 typewriter.","tags":["italian","design","electromechanical","moma","printing","beautiful","compasso-doro"],"rarity_score":9.5,"weirdness_score":7.0},
    {"make":"Olivetti","model":"Programma 101","year_introduced":1965,"calc_type":"programmable","display_type":"other","power_source":"AC","country_of_origin":"Italy","description":"The world's first commercial programmable calculator — a desktop unit that used magnetic card programs. NASA bought 10 of them to calculate trajectories for the Apollo 11 moon landing.","fun_facts":"NASA bought 10 Programma 101s for Apollo 11 calculations. The Italian government later demanded HP pay Olivetti $900,000 in royalties for the HP-9100 which was too similar.","tags":["first","programmable","historic","italian","nasa","apollo","desktop"],"rarity_score":9.8,"weirdness_score":7.5},
    {"make":"Triumph-Adler","model":"ADDO-X 9212","year_introduced":1972,"calc_type":"financial","display_type":"nixie","power_source":"AC","country_of_origin":"West Germany","description":"West German desktop business calculator with a 12-digit nixie tube display. Triumph-Adler was a major typewriter and calculator manufacturer before being absorbed by Volkswagen.","tags":["german","nixie","financial","desktop","west-germany"],"rarity_score":8.5,"weirdness_score":5.0},
    {"make":"Nixdorf","model":"820","year_introduced":1969,"calc_type":"other","display_type":"other","power_source":"AC","country_of_origin":"West Germany","description":"Early electronic desktop calculator from Heinz Nixdorf's company that would later become one of Europe's largest computer manufacturers. Heavy, expensive, and built like a tank.","tags":["german","desktop","historic","early","nixdorf"],"rarity_score":9.0,"weirdness_score":5.5},
    {"make":"Friden","model":"EC-130","year_introduced":1964,"calc_type":"other","display_type":"other","power_source":"AC","country_of_origin":"USA","description":"One of the first all-electronic desktop calculators, using a CRT display to show results. Designed by Robert Ragen and used an elaborate delay-line memory system.","fun_facts":"The EC-130 used a magnetostrictive delay line (a loop of wire) as its memory — sound waves traveled through the wire storing bits.","tags":["crt","historic","first","delay-line","desktop","early"],"rarity_score":9.8,"weirdness_score":9.0},
    {"make":"Monroe","model":"Epic 3000","year_introduced":1974,"calc_type":"programmable","display_type":"LED","power_source":"AC","country_of_origin":"USA","description":"Desktop programmable calculator from Monroe, a major adding machine maker. The Epic series was their push into programmable electronics as their mechanical products became obsolete.","tags":["programmable","desktop","american","adding-machine-era"],"rarity_score":8.5,"weirdness_score":5.0},

    # ── Canon ─────────────────────────────────────────────────────────────
    {"make":"Canon","model":"Pocketronic","year_introduced":1970,"calc_type":"other","display_type":"other","power_source":"battery","country_of_origin":"Japan","description":"The world's first handheld (though barely) electronic calculator using thermal printing output instead of a display. A joint Canon/Texas Instruments project based on TI's Cal-Tech prototype.","fun_facts":"The Pocketronic had no display — results were printed on a paper tape. It weighed 1.7 lbs, which Canon called 'pocket-size.'","tags":["first","handheld","thermal","no-display","historic","joint-venture","ti"],"rarity_score":9.8,"weirdness_score":9.5},
    {"make":"Canon","model":"F-502","year_introduced":1977,"calc_type":"scientific","display_type":"LED","power_source":"battery","num_keys":37,"country_of_origin":"Japan","description":"Slim LED scientific calculator with a distinctive red display. Popular in Japan for its clean design and solid engineering.","tags":["led","scientific","slim","japanese"],"rarity_score":6.5,"weirdness_score":3.5},
    {"make":"Canon","model":"X-07","year_introduced":1983,"calc_type":"programmable","display_type":"LCD","power_source":"battery","country_of_origin":"Japan","description":"Pocket computer running BASIC, compatible with the TRS-80 Model 100. Had a full keyboard and could be expanded with ROM modules for different functions.","tags":["basic","pocket-computer","programmable","modules","trs-80-compatible"],"rarity_score":7.0,"weirdness_score":6.0},

    # ── National Semiconductor / Rockwell ───────────────────────────────
    {"make":"National Semiconductor","model":"Mathematician","year_introduced":1974,"calc_type":"scientific","display_type":"LED","power_source":"battery","num_keys":28,"country_of_origin":"USA","description":"One of National Semiconductor's early LED scientific calculators. NS briefly competed in the calculator market before exiting the segment to focus on semiconductors.","tags":["led","american","vintage","national-semi"],"rarity_score":8.0,"weirdness_score":5.0},
    {"make":"Rockwell","model":"8R","year_introduced":1973,"calc_type":"other","display_type":"LED","power_source":"battery","country_of_origin":"USA","description":"Basic four-function calculator from Rockwell International, who made their own calculator chips. The 8R was a very early example of Rockwell using their own silicon for consumer products.","tags":["led","american","early","four-function","rockwell"],"rarity_score":7.5,"weirdness_score":4.0},
    {"make":"Rockwell","model":"204R","year_introduced":1975,"calc_type":"scientific","display_type":"LED","power_source":"battery","country_of_origin":"USA","description":"Scientific calculator made by Rockwell using their own LED display modules. An interesting piece of vertical integration in the early calculator wars.","tags":["led","scientific","american","rockwell","vertical-integration"],"rarity_score":7.5,"weirdness_score":4.5},

    # ── Sanyo / Toshiba / Citizen ────────────────────────────────────────
    {"make":"Sanyo","model":"ICC-82D","year_introduced":1972,"calc_type":"other","display_type":"LED","power_source":"battery","country_of_origin":"Japan","description":"Early handheld calculator from Sanyo with distinctive red LED display. One of the first Japanese calculators to reach the mass consumer market.","tags":["led","japanese","early","sanyo","consumer"],"rarity_score":8.0,"weirdness_score":5.0},
    {"make":"Toshiba","model":"BC-1411","year_introduced":1967,"calc_type":"other","display_type":"other","power_source":"AC","country_of_origin":"Japan","description":"Early Toshiba electronic desktop calculator. Toshiba was one of the earliest Japanese companies to enter the electronic calculator market alongside Sharp and Casio.","tags":["desktop","early","japanese","toshiba","historic"],"rarity_score":9.5,"weirdness_score":6.0},
    {"make":"Citizen","model":"SR-1D","year_introduced":1977,"calc_type":"scientific","display_type":"LED","power_source":"battery","num_keys":38,"country_of_origin":"Japan","description":"Scientific LED calculator from Citizen Watch, who diversified into calculators in the 1970s. Known for quality construction mirroring their watchmaking precision.","tags":["led","japanese","citizen","watch-company","scientific"],"rarity_score":7.0,"weirdness_score":4.5},
    {"make":"Citizen","model":"SRP-75","year_introduced":1984,"calc_type":"scientific","display_type":"LCD","power_source":"solar","num_keys":40,"country_of_origin":"Japan","description":"Solar-powered scientific calculator from Citizen. Took advantage of their experience in solar watch technology to produce reliable solar calculator products.","tags":["solar","scientific","japanese","citizen","watch-company"],"rarity_score":5.5,"weirdness_score":3.0},

    # ── Compucorp / Wang ─────────────────────────────────────────────────
    {"make":"Compucorp","model":"325 Scientist","year_introduced":1971,"calc_type":"scientific","display_type":"other","power_source":"AC","country_of_origin":"USA","description":"One of the earliest programmable scientific calculators, predating the HP-65. Desktop unit with a nixie display and 80 programming steps. Extraordinarily expensive at $1,995 (1971).","tags":["programmable","scientific","early","expensive","desktop","nixie"],"rarity_score":9.5,"weirdness_score":7.5},
    {"make":"Wang","model":"Model 300","year_introduced":1965,"calc_type":"other","display_type":"other","power_source":"AC","country_of_origin":"USA","description":"An Wang's LOCI (Logarithmic Computing Instrument) desktop calculator. Used logarithms internally to compute multiplication and division — the same technique as a slide rule, but electronically.","fun_facts":"An Wang patented magnetic core memory technology, sold the patent to IBM for $500,000, and used the money to start Wang Laboratories.","tags":["wang","logarithmic","desktop","historic","an-wang","early"],"rarity_score":9.5,"weirdness_score":8.5},

    # ── More novelty and unusual ─────────────────────────────────────────
    {"make":"Casio","model":"TV-400","year_introduced":1983,"calc_type":"novelty","display_type":"LCD","power_source":"battery","country_of_origin":"Japan","description":"Calculator combined with a tiny LCD pocket television. Received UHF/VHF TV signals and displayed them on a 2-inch LCD screen while also functioning as a fully working calculator.","fun_facts":"The TV-400 is the convergence device that predated smartphones by 25 years. It actually worked — you could watch TV on it.","tags":["tv","television","convergence","novelty","lcd","weird"],"rarity_score":9.0,"weirdness_score":9.5},
    {"make":"HP","model":"HP-71B","year_introduced":1984,"calc_type":"programmable","display_type":"LCD","power_source":"battery","country_of_origin":"USA","description":"Handheld BASIC computer from HP that was also a calculator. Could be expanded with ROM modules including FORTH, assembler, chemistry, surveying, and more. Interface loop connector for peripherals.","tags":["basic","programmable","rpn","expandable","il-bus","professional"],"rarity_score":7.5,"weirdness_score":6.0},
    {"make":"Psion","model":"Organiser II","year_introduced":1986,"calc_type":"programmable","display_type":"LCD","power_source":"battery","country_of_origin":"UK","description":"British handheld computer/organizer that included calculator functionality. Used Datapaks for storage — solid-state ROM cartridges. Featured the OPL programming language. An early PDA.","fun_facts":"The Psion Organiser II was used by many London Black Cab drivers in the late 1980s before GPS systems existed.","tags":["british","pda","organizer","programmable","datapak","opl"],"rarity_score":6.5,"weirdness_score":7.0},
    {"make":"Atari","model":"Calculator","year_introduced":1979,"calc_type":"other","display_type":"LED","power_source":"battery","country_of_origin":"USA","description":"A simple four-function LED calculator made by Atari — yes, the video game company. Made during their brief diversification into calculator products. Rare and unexpected for an Atari product.","fun_facts":"Very few people know Atari made a calculator. It was produced for less than a year before Atari refocused entirely on games.","tags":["atari","video-game-company","led","novelty","unexpected","four-function"],"rarity_score":9.5,"weirdness_score":9.5},
    {"make":"Mattel","model":"Auto Race","year_introduced":1976,"calc_type":"novelty","display_type":"LED","power_source":"battery","country_of_origin":"USA","description":"Not really a calculator but uses calculator LED display hardware in a racing game. Widely considered the first handheld electronic game ever sold. Features a vertical LED display showing cars as blinking dots.","fun_facts":"Auto Race (1976) predates the Game & Watch and Microvision. It launched the entire handheld gaming industry.","tags":["first","handheld-game","led","novelty","mattel","historic","racing","toy"],"rarity_score":8.0,"weirdness_score":9.0},
    {"make":"Sinclair","model":"Cambridge Memory","year_introduced":1977,"calc_type":"programmable","display_type":"LED","power_source":"battery","num_keys":24,"country_of_origin":"UK","description":"Programmable version of the Cambridge calculator with 36 program steps. Clive Sinclair's attempt to offer a budget programmable calculator — functional but quirky with its one-line LED display.","tags":["british","sinclair","programmable","budget","led","clive-sinclair"],"rarity_score":8.0,"weirdness_score":7.0},
    {"make":"Sinclair","model":"Scientific Programmable","year_introduced":1975,"calc_type":"programmable","display_type":"LED","power_source":"battery","num_keys":20,"country_of_origin":"UK","description":"Minimalist programmable scientific calculator using just 20 keys for everything. Sinclair's unique multi-function key design reduced costs but made the device notoriously difficult to use.","tags":["british","sinclair","programmable","minimalist","multi-function","led"],"rarity_score":8.5,"weirdness_score":8.0},

    # ── More TI vintage ──────────────────────────────────────────────────
    {"make":"TI","model":"SR-52","year_introduced":1975,"calc_type":"programmable","display_type":"LED","power_source":"battery","num_keys":44,"country_of_origin":"USA","description":"TI's first magnetic card programmable calculator, competing directly with the HP-65. Had 224 program steps and a full library of applications on magnetic cards.","tags":["programmable","magnetic-card","led","vintage","hp-65-rival"],"rarity_score":8.5,"weirdness_score":5.5},
    {"make":"TI","model":"SR-56","year_introduced":1976,"calc_type":"programmable","display_type":"LED","power_source":"battery","num_keys":44,"country_of_origin":"USA","description":"TI's 100-step programmable calculator without magnetic cards. The 'SR' stood for Slide Rule. More affordable than the SR-52 and popular with university students.","tags":["programmable","led","vintage","slide-rule","affordable"],"rarity_score":7.5,"weirdness_score":4.5},
    {"make":"TI","model":"CC-40","year_introduced":1983,"calc_type":"programmable","display_type":"LCD","power_source":"battery","country_of_origin":"USA","description":"TI's BASIC pocket computer using CMOS technology for long battery life. Had a full keyboard and could be expanded with solid-state modules. TI's answer to the Casio FX-702P.","tags":["basic","pocket-computer","cmos","programmable","ti","modules"],"rarity_score":7.0,"weirdness_score":5.5},
    {"make":"TI","model":"TI-95 PROCALC","year_introduced":1985,"calc_type":"programmable","display_type":"LCD","power_source":"battery","num_keys":51,"country_of_origin":"USA","description":"TI's most advanced programmable calculator before the graphing era. Could be expanded with Solid State Software (SSS) modules and had assembly language programming capability.","tags":["programmable","sss-modules","assembly","professional","vintage"],"rarity_score":7.5,"weirdness_score":5.5},
    {"make":"TI","model":"TI-55","year_introduced":1977,"calc_type":"programmable","display_type":"LED","power_source":"battery","num_keys":40,"country_of_origin":"USA","description":"Affordable TI programmable calculator with 32 steps. Positioned between the basic scientific calculators and the more expensive programmable models.","tags":["programmable","led","affordable","ti","vintage"],"rarity_score":6.0,"weirdness_score":3.5},

    # ── More HP ──────────────────────────────────────────────────────────
    {"make":"HP","model":"HP-25","year_introduced":1975,"calc_type":"programmable","display_type":"LED","power_source":"battery","num_keys":35,"country_of_origin":"USA","description":"HP's entry-level programmable calculator without magnetic card reader. 49 program steps. A cheaper alternative to the HP-65 that brought programmability to more users.","tags":["programmable","rpn","led","affordable","vintage"],"rarity_score":7.5,"weirdness_score":4.5},
    {"make":"HP","model":"HP-34C","year_introduced":1979,"calc_type":"programmable","display_type":"LED","power_source":"battery","num_keys":35,"country_of_origin":"USA","description":"Continuous memory programmable calculator — programs remained in memory even when turned off, achieved through a special low-power mode. Featured SOLVE and INTEGRATE functions.","tags":["continuous-memory","programmable","rpn","led","solve","integrate"],"rarity_score":7.5,"weirdness_score":5.0},
    {"make":"HP","model":"HP-15C","year_introduced":1982,"calc_type":"scientific","display_type":"LCD","power_source":"battery","num_keys":35,"country_of_origin":"USA","description":"HP's legendary scientific calculator with matrix operations and complex number support. Beloved by scientists and engineers worldwide. Reissued in 2011 and again in 2023 due to demand.","fun_facts":"The HP-15C was reissued in 2023 — 41 years after its original release — because demand from collectors never died. It sells for $120 new today.","tags":["rpn","scientific","matrix","complex","classic","reissued","beloved"],"rarity_score":6.5,"weirdness_score":4.0},
    {"make":"HP","model":"HP-19C","year_introduced":1977,"calc_type":"programmable","display_type":"LED","power_source":"battery","country_of_origin":"USA","description":"Printing programmable calculator — the HP-19C had a built-in thermal printer. Could print programs, calculations, and results on narrow paper tape. Essentially an HP-29C with a printer.","tags":["printing","programmable","rpn","led","thermal","printer-built-in"],"rarity_score":8.5,"weirdness_score":7.5},

    # ── More Casio ───────────────────────────────────────────────────────
    {"make":"Casio","model":"CFX-9850GB Plus","year_introduced":1996,"calc_type":"graphing","display_type":"LCD","power_source":"battery","num_keys":62,"country_of_origin":"Japan","description":"One of the first color graphing calculators — three-color LCD (orange, blue, green) for different graph lines. Extremely popular in Europe and Asia for high school and university use.","tags":["color","graphing","three-color","popular","european","vintage"],"rarity_score":5.0,"weirdness_score":5.0},
    {"make":"Casio","model":"fx-4000P","year_introduced":1989,"calc_type":"programmable","display_type":"LCD","power_source":"battery","num_keys":44,"country_of_origin":"Japan","description":"Formula-programmable scientific calculator storing formulas rather than step-by-step programs. Different paradigm from TI/HP programmables — users stored often-used formulas for quick recall.","tags":["programmable","formula","scientific","japanese","unusual-paradigm"],"rarity_score":5.5,"weirdness_score":5.0},
    {"make":"Casio","model":"AT-550","year_introduced":1984,"calc_type":"databank","display_type":"LCD","power_source":"battery","country_of_origin":"Japan","description":"Calculator watch with a full databank for storing phone numbers, schedules, and notes. Predicted the smartwatch by 30 years.","tags":["watch","databank","wristwatch","smartwatch-ancestor","vintage"],"rarity_score":7.0,"weirdness_score":8.0},
    {"make":"Casio","model":"SL-300SV","year_introduced":1988,"calc_type":"other","display_type":"LCD","power_source":"solar","country_of_origin":"Japan","description":"Ultra-thin credit card calculator running entirely on solar power. At 3.9mm thick, one of the thinnest calculators ever made. Still in production in various forms today.","tags":["solar","thin","credit-card","slim","iconic"],"rarity_score":2.0,"weirdness_score":2.5},

    # ── Hewlett-Packard oddities ─────────────────────────────────────────
    {"make":"HP","model":"HP-75C","year_introduced":1982,"calc_type":"programmable","display_type":"LCD","power_source":"battery","country_of_origin":"USA","description":"HP's horizontal-format BASIC pocket computer. Designed to lie flat on a desk with a full calculator-style keyboard. Had a built-in clock/calendar and HP-IL interface for connecting peripherals.","tags":["basic","horizontal","programmable","il-bus","clock","pocket-computer"],"rarity_score":8.0,"weirdness_score":7.5},
    {"make":"HP","model":"HP-91","year_introduced":1976,"calc_type":"scientific","display_type":"LED","power_source":"battery","num_keys":35,"country_of_origin":"USA","description":"Desktop printing scientific calculator — combining a full HP-35 style keyboard with a built-in thermal printer. Designed for lab use where a permanent record was needed.","tags":["printing","scientific","rpn","led","desktop","thermal","lab"],"rarity_score":8.5,"weirdness_score":6.5},
]


async def seed():
    engine = create_async_engine(DATABASE_URL.replace("postgresql://", "postgresql+asyncpg://") if "asyncpg" not in DATABASE_URL else DATABASE_URL)
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    # Import here so the models register
    import importlib.util, pathlib
    backend_path = pathlib.Path(__file__).parent.parent / "backend"
    sys.path.insert(0, str(backend_path))

    from app.models.calculator import Calculator

    async with async_session() as session:
        added = 0
        skipped = 0
        for data in CALCULATORS:
            # Check for existing by make+model
            result = await session.execute(
                select(Calculator).where(
                    and_(Calculator.make == data["make"], Calculator.model == data["model"])
                )
            )
            existing = result.scalar_one_or_none()
            if existing:
                skipped += 1
                continue

            calc = Calculator(
                make=data["make"],
                model=data["model"],
                year_introduced=data.get("year_introduced"),
                year_discontinued=data.get("year_discontinued"),
                calc_type=data.get("calc_type", "other"),
                display_type=data.get("display_type"),
                power_source=data.get("power_source"),
                num_keys=data.get("num_keys"),
                country_of_origin=data.get("country_of_origin"),
                description=data.get("description"),
                fun_facts=data.get("fun_facts"),
                tags=data.get("tags", []),
                rarity_score=data.get("rarity_score"),
                weirdness_score=data.get("weirdness_score"),
                images=[],
                external_refs={},
                is_verified=True,
            )
            session.add(calc)
            added += 1

        await session.commit()
        print(f"✅ Added {added} calculators, skipped {skipped} duplicates")
        print(f"   Total in CALCULATORS list: {len(CALCULATORS)}")

    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(seed())
