#!/usr/bin/env python3
"""
Seed missing HP and TI calculators.
Run: docker compose exec backend python /scripts/seed_missing_hp_ti.py
"""
import asyncio, os, sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent.parent / "backend"))

DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql+asyncpg://curiocalc:changeme@localhost:5432/curiocalc",
)

CALCS = [
    # ══════════════════════════════════════════════════════════════════
    # HP — Classic Desktop (pre-pocket era)
    # ══════════════════════════════════════════════════════════════════
    {
        "make": "HP", "model": "HP-9100A",
        "year_introduced": 1968, "year_discontinued": 1970,
        "calc_type": "scientific", "display_type": "CRT",
        "power_source": "AC",
        "tags": ["vintage", "desktop", "programmable", "historic"],
        "rarity_score": 9.8, "weirdness_score": 8.5,
        "description": "HP's very first calculator — a desktop scientific with a built-in CRT display. Predated the pocket calculator era by four years and cost $4,900 at launch. Used magnetic card storage for program memory.",
        "fun_facts": "The HP-9100A was so advanced that HP marketed it as a 'personal computer' — they were afraid the term 'calculator' would make customers think it was a toy.",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/HP_9100A.jpg/480px-HP_9100A.jpg"],
    },
    {
        "make": "HP", "model": "HP-9810A",
        "year_introduced": 1971, "year_discontinued": 1975,
        "calc_type": "programmable", "display_type": "LED",
        "power_source": "AC",
        "tags": ["vintage", "desktop", "programmable"],
        "rarity_score": 9.2, "weirdness_score": 7.0,
        "description": "Part of HP's 9800 series desktop programmable calculators. RPN with plug-in ROM modules for extended functions.",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/HP_9810A.jpg/480px-HP_9810A.jpg"],
    },
    {
        "make": "HP", "model": "HP-9820A",
        "year_introduced": 1971, "year_discontinued": 1975,
        "calc_type": "programmable", "display_type": "LED",
        "power_source": "AC",
        "tags": ["vintage", "desktop", "programmable"],
        "rarity_score": 9.2, "weirdness_score": 7.0,
        "description": "Desktop programmable calculator with algebraic notation. Part of the HP 9800 series alongside the 9810A and 9830A.",
        "images": [],
    },
    {
        "make": "HP", "model": "HP-9830A",
        "year_introduced": 1972, "year_discontinued": 1975,
        "calc_type": "programmable", "display_type": "LED",
        "power_source": "AC",
        "tags": ["vintage", "desktop", "programmable", "basic"],
        "rarity_score": 9.3, "weirdness_score": 7.5,
        "description": "The most capable of the HP 9800 series. Used a BASIC-like programming language and could be connected to peripherals including a printer and cassette storage.",
        "images": [],
    },
    # ══════════════════════════════════════════════════════════════════
    # HP — Woodstock / missing LED era
    # ══════════════════════════════════════════════════════════════════
    {
        "make": "HP", "model": "HP-92",
        "year_introduced": 1977, "year_discontinued": 1981,
        "calc_type": "financial", "display_type": "LED",
        "power_source": "Battery",
        "tags": ["financial", "vintage", "printing"],
        "rarity_score": 8.5, "weirdness_score": 6.0,
        "description": "HP's financial printing calculator from the Topcat series. Combined a full financial calculator with a thermal printer.",
        "images": [],
    },
    {
        "make": "HP", "model": "HP-10",
        "year_introduced": 1978, "year_discontinued": 1983,
        "calc_type": "printing", "display_type": "LED",
        "power_source": "Battery",
        "tags": ["printing", "vintage"],
        "rarity_score": 7.8, "weirdness_score": 5.5,
        "description": "HP's first printing calculator with a built-in thermal printer. Four-function with basic business features.",
        "images": [],
    },
    # ══════════════════════════════════════════════════════════════════
    # HP — Pioneer series additions
    # ══════════════════════════════════════════════════════════════════
    {
        "make": "HP", "model": "HP-10B",
        "year_introduced": 1988, "year_discontinued": 2001,
        "calc_type": "financial", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 38,
        "country_of_origin": "Singapore",
        "tags": ["financial", "pioneer"],
        "rarity_score": 4.5, "weirdness_score": 2.0,
        "description": "HP's entry-level business calculator. Covered TVM, amortization, and basic statistics in an affordable package.",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/HP10B.jpg/480px-HP10B.jpg"],
    },
    {
        "make": "HP", "model": "HP-14B",
        "year_introduced": 1988, "year_discontinued": 1992,
        "calc_type": "financial", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 36,
        "tags": ["financial", "pioneer"],
        "rarity_score": 7.0, "weirdness_score": 3.0,
        "description": "Business calculator from the Pioneer series with basic financial functions. Less featured than the HP-17B but more affordable.",
        "images": [],
    },
    {
        "make": "HP", "model": "HP-48G+",
        "year_introduced": 1998, "year_discontinued": 2003,
        "calc_type": "graphing", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 49,
        "country_of_origin": "Indonesia",
        "tags": ["graphing", "rpn", "programmable", "cas"],
        "rarity_score": 6.0, "weirdness_score": 4.5,
        "description": "Upgraded HP-48G with 128KB of RAM (vs 32KB in the original). Compatible with all HP-48G software and peripherals.",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/HP-48GX_calculator_%2823588938468%29.jpg/480px-HP-48GX_calculator_%2823588938468%29.jpg"],
    },
    # ══════════════════════════════════════════════════════════════════
    # HP — Modern financial
    # ══════════════════════════════════════════════════════════════════
    {
        "make": "HP", "model": "HP-10BII",
        "year_introduced": 2001, "year_discontinued": 2010,
        "calc_type": "financial", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 43,
        "tags": ["financial"],
        "rarity_score": 3.5, "weirdness_score": 1.5,
        "description": "Second-generation HP-10B with more functions, larger display, and algebraic entry. Popular in business courses.",
        "images": [],
    },
    {
        "make": "HP", "model": "HP-10bII+",
        "year_introduced": 2010,
        "calc_type": "financial", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 43,
        "tags": ["financial", "modern"],
        "rarity_score": 2.5, "weirdness_score": 1.0,
        "description": "Current HP entry-level financial calculator. Multi-line display, 170+ functions, and CFA exam approval.",
        "images": [],
    },
    {
        "make": "HP", "model": "HP-17bII+",
        "year_introduced": 2003,
        "calc_type": "financial", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 35,
        "tags": ["financial", "modern", "rpn"],
        "rarity_score": 4.0, "weirdness_score": 2.5,
        "description": "Modern re-issue of the classic HP-17BII. Supports both RPN and algebraic entry modes. Still widely used by finance professionals.",
        "images": [],
    },
    {
        "make": "HP", "model": "HP-20b",
        "year_introduced": 2008, "year_discontinued": 2015,
        "calc_type": "financial", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 30,
        "tags": ["financial", "modern"],
        "rarity_score": 5.0, "weirdness_score": 3.0,
        "description": "Business consultant financial calculator with two-line LCD and over 250 built-in functions. Also famous as the base hardware for the WP 34S scientific firmware.",
        "fun_facts": "The HP-20b and HP-30b became cult favorites among RPN enthusiasts who flashed them with the open-source WP 34S scientific calculator firmware.",
        "images": [],
    },
    {
        "make": "HP", "model": "HP-30b",
        "year_introduced": 2010, "year_discontinued": 2015,
        "calc_type": "financial", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 31,
        "tags": ["financial", "modern", "hackable"],
        "rarity_score": 5.5, "weirdness_score": 4.0,
        "description": "Business professional financial calculator. Like the HP-20b, became famous in the RPN community as WP 34S flash hardware.",
        "fun_facts": "With the WP 34S open-source firmware, the HP-30b transforms into one of the most powerful scientific RPN calculators ever made.",
        "images": [],
    },
    # ══════════════════════════════════════════════════════════════════
    # HP — Modern scientific
    # ══════════════════════════════════════════════════════════════════
    {
        "make": "HP", "model": "HP-6S",
        "year_introduced": 1997, "year_discontinued": 2003,
        "calc_type": "scientific", "display_type": "LCD",
        "power_source": "Battery",
        "tags": ["scientific", "student"],
        "rarity_score": 3.0, "weirdness_score": 1.5,
        "description": "Budget scientific calculator aimed at students. Algebraic entry with 240 functions.",
        "images": [],
    },
    {
        "make": "HP", "model": "HP-6S Solar",
        "year_introduced": 1999,
        "calc_type": "scientific", "display_type": "LCD",
        "power_source": "Solar",
        "tags": ["scientific", "student", "solar"],
        "rarity_score": 3.0, "weirdness_score": 1.5,
        "description": "Solar-powered variant of the HP-6S student scientific calculator.",
        "images": [],
    },
    {
        "make": "HP", "model": "HP-9S",
        "year_introduced": 2000,
        "calc_type": "scientific", "display_type": "LCD",
        "power_source": "Battery",
        "tags": ["scientific", "student"],
        "rarity_score": 3.5, "weirdness_score": 2.0,
        "description": "Mid-range scientific calculator with 279 functions and two-line display.",
        "images": [],
    },
    {
        "make": "HP", "model": "HP-30S",
        "year_introduced": 2000,
        "calc_type": "scientific", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 32,
        "tags": ["scientific", "student"],
        "rarity_score": 3.5, "weirdness_score": 2.0,
        "description": "Scientific calculator with 30 scientific functions, fraction arithmetic, and base conversion.",
        "images": [],
    },
    {
        "make": "HP", "model": "HP-33S",
        "year_introduced": 2003, "year_discontinued": 2014,
        "calc_type": "scientific", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 43,
        "tags": ["scientific", "rpn", "programmable"],
        "rarity_score": 5.5, "weirdness_score": 5.5,
        "description": "Scientific RPN calculator with 32KB of memory and 31 registers. Successor to the HP-32SII. Controversial diamond-shaped key layout.",
        "fun_facts": "The HP-33S was HP's attempt to modernize the HP-32SII but its unusual diamond key layout was widely criticized as ergonomically inferior to its predecessor.",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/HP-33S_calculator.jpg/480px-HP-33S_calculator.jpg"],
    },
    {
        "make": "HP", "model": "HP-9G",
        "year_introduced": 2003,
        "calc_type": "graphing", "display_type": "LCD",
        "power_source": "Battery",
        "tags": ["graphing", "student"],
        "rarity_score": 4.0, "weirdness_score": 3.0,
        "description": "Budget graphing calculator for students. 250 functions, basic equation solving, and graph plotting.",
        "images": [],
    },
    {
        "make": "HP", "model": "HP-39G+",
        "year_introduced": 2003, "year_discontinued": 2006,
        "calc_type": "graphing", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 50,
        "country_of_origin": "China",
        "tags": ["graphing", "student"],
        "rarity_score": 5.0, "weirdness_score": 3.5,
        "description": "Upgraded HP-39G with faster processor and more memory. Designed for high school students with built-in equation library.",
        "images": [],
    },
    {
        "make": "HP", "model": "HP-40GS",
        "year_introduced": 2006, "year_discontinued": 2010,
        "calc_type": "graphing", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 50,
        "tags": ["graphing", "cas", "student"],
        "rarity_score": 5.5, "weirdness_score": 4.0,
        "description": "Graphing calculator with CAS (Computer Algebra System). Based on the HP-39G+ hardware with CAS firmware added.",
        "images": [],
    },
    {
        "make": "HP", "model": "HP SmartCalc 300S",
        "year_introduced": 2009,
        "calc_type": "scientific", "display_type": "LCD",
        "power_source": "Battery",
        "tags": ["scientific", "student", "natural-display"],
        "rarity_score": 2.5, "weirdness_score": 2.0,
        "description": "Natural Textbook Display scientific calculator showing expressions as written on paper. HP's entry into the natural-display market segment.",
        "images": [],
    },
    {
        "make": "HP", "model": "HP-15C Collector's Edition",
        "year_introduced": 2023,
        "calc_type": "scientific", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 35,
        "tags": ["scientific", "rpn", "programmable", "modern", "collectors"],
        "rarity_score": 6.5, "weirdness_score": 4.0,
        "description": "Latest revival of the legendary HP-15C, now with a ARM Cortex processor running 100x faster than the original. Retains full compatibility with 40-year-old programs.",
        "images": [],
    },
    {
        "make": "HP", "model": "HP-12C Prestige",
        "year_introduced": 2003,
        "calc_type": "financial", "display_type": "LCD",
        "power_source": "Battery",
        "tags": ["financial", "rpn"],
        "rarity_score": 5.0, "weirdness_score": 2.5,
        "description": "Luxury version of the HP-12C with a brushed metal case and blue accent keys. Same functions as the standard 12C.",
        "images": [],
    },
    # ══════════════════════════════════════════════════════════════════
    # TI — Graphing calculators (all major models)
    # ══════════════════════════════════════════════════════════════════
    {
        "make": "TI", "model": "TI-81",
        "year_introduced": 1990, "year_discontinued": 1995,
        "calc_type": "graphing", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 46,
        "country_of_origin": "Taiwan",
        "tags": ["graphing", "student", "vintage"],
        "rarity_score": 7.0, "weirdness_score": 3.5,
        "description": "Texas Instruments' first graphing calculator and the one that started the graphing revolution in classrooms. No link port and limited memory by later standards, but it changed math education forever.",
        "fun_facts": "The TI-81 had no way to connect to a computer or other calculators — every program had to be typed in by hand. Despite this limitation, it became a massive hit in US high schools.",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/TI-81.png/480px-TI-81.png"],
    },
    {
        "make": "TI", "model": "TI-82",
        "year_introduced": 1993, "year_discontinued": 2004,
        "calc_type": "graphing", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 48,
        "country_of_origin": "Taiwan",
        "tags": ["graphing", "student"],
        "rarity_score": 5.0, "weirdness_score": 3.0,
        "description": "Successor to the TI-81 with a link port for calculator-to-calculator data transfer, more memory, and improved statistics features. Hugely popular in US schools.",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/TI-82.png/480px-TI-82.png"],
    },
    {
        "make": "TI", "model": "TI-83",
        "year_introduced": 1996, "year_discontinued": 2004,
        "calc_type": "graphing", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 50,
        "country_of_origin": "Taiwan",
        "tags": ["graphing", "student"],
        "rarity_score": 4.5, "weirdness_score": 3.0,
        "description": "Upgraded TI-82 with more memory, improved statistics, finance functions, and a faster processor. Immediately popular at the time of release and remained in classrooms for years.",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/TI-83Plus.jpg/480px-TI-83Plus.jpg"],
    },
    {
        "make": "TI", "model": "TI-83 Plus Silver Edition",
        "year_introduced": 2001, "year_discontinued": 2011,
        "calc_type": "graphing", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 50,
        "tags": ["graphing", "student", "expandable"],
        "rarity_score": 4.0, "weirdness_score": 3.0,
        "description": "Upgraded TI-83 Plus with 9× more RAM, 9× more flash memory, and a faster processor. Silver faceplate and higher-contrast display.",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/TI83_Silver.jpg/480px-TI83_Silver.jpg"],
    },
    {
        "make": "TI", "model": "TI-84 Plus C Silver Edition",
        "year_introduced": 2013, "year_discontinued": 2015,
        "calc_type": "graphing", "display_type": "color LCD",
        "power_source": "Battery", "num_keys": 50,
        "tags": ["graphing", "student", "color"],
        "rarity_score": 4.5, "weirdness_score": 3.5,
        "description": "First TI-84 with a color screen. Rechargeable lithium battery. Transitional model bridging the TI-84 Plus Silver Edition and TI-84 Plus CE.",
        "images": [],
    },
    {
        "make": "TI", "model": "TI-84 Plus CE",
        "year_introduced": 2015,
        "calc_type": "graphing", "display_type": "color LCD",
        "power_source": "Battery", "num_keys": 50,
        "country_of_origin": "China",
        "tags": ["graphing", "student", "color", "modern"],
        "rarity_score": 2.5, "weirdness_score": 2.0,
        "description": "Slim, color-screen TI-84 with a rechargeable battery. Thinner and lighter than previous TI-84 models while retaining full software compatibility. The current dominant US high school graphing calculator.",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/TI-84_Plus_CE.jpg/480px-TI-84_Plus_CE.jpg"],
    },
    {
        "make": "TI", "model": "TI-84 Plus T",
        "year_introduced": 2016,
        "calc_type": "graphing", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 50,
        "tags": ["graphing", "student", "european"],
        "rarity_score": 4.0, "weirdness_score": 2.5,
        "description": "European version of the TI-84 Plus approved for use in Dutch, German, and other European national exams. Limited to examination-mode functions.",
        "images": [],
    },
    {
        "make": "TI", "model": "TI-84 Plus CE-T",
        "year_introduced": 2018,
        "calc_type": "graphing", "display_type": "color LCD",
        "power_source": "Battery", "num_keys": 50,
        "tags": ["graphing", "student", "european", "color"],
        "rarity_score": 3.5, "weirdness_score": 2.5,
        "description": "European edition of the TI-84 Plus CE with exam-mode lock down for European standardized tests.",
        "images": [],
    },
    {
        "make": "TI", "model": "TI-84 Plus CE Python",
        "year_introduced": 2020,
        "calc_type": "graphing", "display_type": "color LCD",
        "power_source": "Battery", "num_keys": 50,
        "tags": ["graphing", "student", "color", "python", "modern"],
        "rarity_score": 2.0, "weirdness_score": 2.5,
        "description": "TI-84 Plus CE with a built-in Python programming environment. Brings Python to the TI-84 platform for the first time.",
        "images": [],
    },
    {
        "make": "TI", "model": "TI-85",
        "year_introduced": 1992, "year_discontinued": 1999,
        "calc_type": "graphing", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 50,
        "country_of_origin": "Taiwan",
        "tags": ["graphing", "vintage", "engineering"],
        "rarity_score": 6.0, "weirdness_score": 3.5,
        "description": "TI's high-end graphing calculator aimed at college engineering and science students. Faster processor and more memory than the TI-82 with a different key layout optimized for advanced math.",
        "fun_facts": "The TI-85 used a Z80 processor running at 6 MHz — engineers loved it but it was never officially SAT/ACT approved, which limited its high school market penetration.",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/TI-85.png/480px-TI-85.png"],
    },
    {
        "make": "TI", "model": "TI-86",
        "year_introduced": 1997, "year_discontinued": 2004,
        "calc_type": "graphing", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 50,
        "country_of_origin": "Taiwan",
        "tags": ["graphing", "engineering"],
        "rarity_score": 5.5, "weirdness_score": 3.5,
        "description": "Successor to the TI-85 with link cable support, 128KB RAM, and backwards compatibility with TI-85 programs.",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/TI-86.png/480px-TI-86.png"],
    },
    {
        "make": "TI", "model": "TI-89",
        "year_introduced": 1998, "year_discontinued": 2004,
        "calc_type": "graphing", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 50,
        "country_of_origin": "China",
        "tags": ["graphing", "cas", "programmable"],
        "rarity_score": 5.5, "weirdness_score": 4.5,
        "description": "TI's first CAS (Computer Algebra System) graphing calculator. Could perform symbolic differentiation, integration, and algebra manipulation — banned from many standardized tests for being too powerful.",
        "fun_facts": "The TI-89 was so capable that College Board banned it from the SAT. Students and teachers referred to it as 'the calculator you weren't supposed to have.'",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/TI-89_Titanium_1.jpg/480px-TI-89_Titanium_1.jpg"],
    },
    {
        "make": "TI", "model": "TI-92",
        "year_introduced": 1995, "year_discontinued": 1999,
        "calc_type": "graphing", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 75,
        "tags": ["graphing", "cas", "qwerty", "vintage"],
        "rarity_score": 7.0, "weirdness_score": 8.0,
        "description": "Enormous graphing/CAS calculator with a full QWERTY keyboard. Based on the same Motorola 68000 architecture as the early Macintosh. Too large for most exam policies.",
        "fun_facts": "The TI-92 is so large it was banned from standardized tests not for being too powerful — but because it has a QWERTY keyboard, which makes it look like a computer.",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/TI-92.jpg/480px-TI-92.jpg"],
    },
    {
        "make": "TI", "model": "TI-92 Plus",
        "year_introduced": 1999, "year_discontinued": 2002,
        "calc_type": "graphing", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 75,
        "tags": ["graphing", "cas", "qwerty"],
        "rarity_score": 7.5, "weirdness_score": 8.0,
        "description": "Upgraded TI-92 with more flash memory, the Voyage 200/TI-89 Apps compatibility, and Pretty Print display. Merger of TI-92 and TI-89 capabilities.",
        "images": [],
    },
    {
        "make": "TI", "model": "TI-Nspire",
        "year_introduced": 2007, "year_discontinued": 2011,
        "calc_type": "graphing", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 65,
        "tags": ["graphing", "modern", "touchpad"],
        "rarity_score": 4.5, "weirdness_score": 4.0,
        "description": "TI's first Nspire-series calculator. Introduced the clickpad navigation system and computer-like document-based interface. The keypad could be swapped with a TI-84 Plus keypad.",
        "fun_facts": "Early TI-Nspire units shipped with a snap-on TI-84 Plus keypad in the box, allowing teachers to use it in TI-84 mode during the transition period.",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/TI-Nspire.jpg/480px-TI-Nspire.jpg"],
    },
    {
        "make": "TI", "model": "TI-Nspire CAS",
        "year_introduced": 2007, "year_discontinued": 2011,
        "calc_type": "graphing", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 65,
        "tags": ["graphing", "cas", "modern"],
        "rarity_score": 5.0, "weirdness_score": 4.5,
        "description": "CAS version of the original TI-Nspire. Full symbolic math engine supporting algebraic manipulation, symbolic differentiation and integration.",
        "images": [],
    },
    {
        "make": "TI", "model": "TI-Nspire CX",
        "year_introduced": 2011,
        "calc_type": "graphing", "display_type": "color LCD",
        "power_source": "Battery", "num_keys": 65,
        "country_of_origin": "China",
        "tags": ["graphing", "color", "modern", "3d"],
        "rarity_score": 3.5, "weirdness_score": 3.5,
        "description": "Color-screen Nspire with a slim profile and rechargeable battery. Added 3D graphing capability and a full-color 320×240 display. Massive upgrade over previous Nspire models.",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/TI-Nspire-CX.jpg/480px-TI-Nspire-CX.jpg"],
    },
    {
        "make": "TI", "model": "TI-Nspire CX II",
        "year_introduced": 2019,
        "calc_type": "graphing", "display_type": "color LCD",
        "power_source": "Battery", "num_keys": 65,
        "tags": ["graphing", "color", "modern", "python"],
        "rarity_score": 2.5, "weirdness_score": 3.0,
        "description": "Second-generation Nspire CX with a faster processor (5× faster than CX), Python programming support, and improved battery life.",
        "images": [],
    },
    {
        "make": "TI", "model": "TI-Nspire CX II CAS",
        "year_introduced": 2019,
        "calc_type": "graphing", "display_type": "color LCD",
        "power_source": "Battery", "num_keys": 65,
        "tags": ["graphing", "color", "cas", "modern", "python"],
        "rarity_score": 3.0, "weirdness_score": 3.5,
        "description": "CAS version of the TI-Nspire CX II. Most powerful TI calculator ever produced for general sale, with Python support, CAS, and 5× faster processor.",
        "images": [],
    },
    {
        "make": "TI", "model": "TI-Nspire CX II-T",
        "year_introduced": 2019,
        "calc_type": "graphing", "display_type": "color LCD",
        "power_source": "Battery", "num_keys": 65,
        "tags": ["graphing", "color", "modern", "european"],
        "rarity_score": 3.5, "weirdness_score": 3.0,
        "description": "European edition of the TI-Nspire CX II. Designed for use in European standardized exams with exam-mode restrictions.",
        "images": [],
    },
    {
        "make": "TI", "model": "TI-Nspire CX II-T CAS",
        "year_introduced": 2019,
        "calc_type": "graphing", "display_type": "color LCD",
        "power_source": "Battery", "num_keys": 65,
        "tags": ["graphing", "color", "cas", "modern", "european"],
        "rarity_score": 3.5, "weirdness_score": 3.5,
        "description": "CAS European edition of the TI-Nspire CX II. Widely used in German, French, and Swiss high school exams.",
        "images": [],
    },
    # ══════════════════════════════════════════════════════════════════
    # TI — Scientific / Student (missing modern models)
    # ══════════════════════════════════════════════════════════════════
    {
        "make": "TI", "model": "TI-73 Explorer",
        "year_introduced": 2003,
        "calc_type": "graphing", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 47,
        "tags": ["graphing", "student", "middle-school"],
        "rarity_score": 4.0, "weirdness_score": 3.0,
        "description": "Graphing calculator designed specifically for middle school students (grades 6–8). Fraction features, data collection, and simplified interface compared to the TI-83/84 series.",
        "images": [],
    },
    {
        "make": "TI", "model": "TI-30X IIS",
        "year_introduced": 1999,
        "calc_type": "scientific", "display_type": "LCD",
        "power_source": "Solar+Battery", "num_keys": 40,
        "tags": ["scientific", "student", "solar", "two-line"],
        "rarity_score": 2.0, "weirdness_score": 1.5,
        "description": "Two-line scientific calculator with solar power. One of the most popular scientific calculators in US middle and high schools. Standard exam tool.",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/TI-30X_IIS.jpg/480px-TI-30X_IIS.jpg"],
    },
    {
        "make": "TI", "model": "TI-30X IIB",
        "year_introduced": 1999,
        "calc_type": "scientific", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 40,
        "tags": ["scientific", "student", "two-line"],
        "rarity_score": 2.0, "weirdness_score": 1.5,
        "description": "Battery-only version of the TI-30X IIS. Same functionality without the solar charging capability.",
        "images": [],
    },
    {
        "make": "TI", "model": "TI-30XS MultiView",
        "year_introduced": 2007,
        "calc_type": "scientific", "display_type": "LCD",
        "power_source": "Solar+Battery", "num_keys": 40,
        "tags": ["scientific", "student", "multiview", "solar"],
        "rarity_score": 2.0, "weirdness_score": 1.5,
        "description": "Four-line scientific calculator with MathPrint technology that displays fractions and expressions as written on paper. Standard in US schools.",
        "images": [],
    },
    {
        "make": "TI", "model": "TI-30X Pro MultiView",
        "year_introduced": 2012,
        "calc_type": "scientific", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 40,
        "tags": ["scientific", "student", "multiview", "cas"],
        "rarity_score": 3.0, "weirdness_score": 2.5,
        "description": "Advanced scientific with basic CAS features. Approved for use in IB and A-level exams in Europe. Includes equation solver and numeric derivatives.",
        "images": [],
    },
    {
        "make": "TI", "model": "TI-34 MultiView",
        "year_introduced": 2007,
        "calc_type": "scientific", "display_type": "LCD",
        "power_source": "Solar+Battery", "num_keys": 35,
        "tags": ["scientific", "student", "multiview", "middle-school"],
        "rarity_score": 2.0, "weirdness_score": 1.5,
        "description": "Scientific calculator for middle school with MathPrint display. Includes fraction operations and data list editor.",
        "images": [],
    },
    {
        "make": "TI", "model": "TI-34 II Explorer Plus",
        "year_introduced": 2004,
        "calc_type": "scientific", "display_type": "LCD",
        "power_source": "Solar+Battery", "num_keys": 35,
        "tags": ["scientific", "student", "solar"],
        "rarity_score": 2.5, "weirdness_score": 1.5,
        "description": "Pre-MultiView TI-34 with two-line display. Designed for middle school with fraction simplification and order of operations guidance.",
        "images": [],
    },
    {
        "make": "TI", "model": "TI-36X Pro",
        "year_introduced": 2011,
        "calc_type": "scientific", "display_type": "LCD",
        "power_source": "Solar+Battery", "num_keys": 52,
        "tags": ["scientific", "engineering", "multiview"],
        "rarity_score": 2.5, "weirdness_score": 2.0,
        "description": "TI's most advanced non-graphing scientific. Solves systems of equations, calculates derivatives/integrals numerically, converts units, and handles complex numbers. Popular with engineers.",
        "images": [],
    },
    {
        "make": "TI", "model": "TI-36X II",
        "year_introduced": 1999, "year_discontinued": 2011,
        "calc_type": "scientific", "display_type": "LCD",
        "power_source": "Solar+Battery", "num_keys": 44,
        "tags": ["scientific", "engineering"],
        "rarity_score": 3.5, "weirdness_score": 2.0,
        "description": "Two-line scientific calculator with base conversions and complex numbers. Predecessor to the TI-36X Pro.",
        "images": [],
    },
    {
        "make": "TI", "model": "TI-15 Explorer",
        "year_introduced": 2000,
        "calc_type": "scientific", "display_type": "LCD",
        "power_source": "Solar+Battery", "num_keys": 32,
        "tags": ["scientific", "student", "elementary"],
        "rarity_score": 3.0, "weirdness_score": 2.5,
        "description": "Elementary school calculator with fraction display, problem solving mode, and multiple representations. Designed for grades 3–6.",
        "images": [],
    },
    {
        "make": "TI", "model": "BA II Plus Professional",
        "year_introduced": 2004,
        "calc_type": "financial", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 40,
        "tags": ["financial", "professional", "cfa"],
        "rarity_score": 3.5, "weirdness_score": 2.0,
        "description": "Advanced version of the BA II Plus. Adds NFV, modified duration, and a modified IRR function. Approved by CFA Institute for the CFA exam alongside the HP-12C.",
        "fun_facts": "The BA II Plus Professional is one of only two calculators permitted in the CFA exam — the other being the HP-12C. These two models effectively have a duopoly in professional finance education.",
        "images": [],
    },
    {
        "make": "TI", "model": "TI-66",
        "year_introduced": 1983, "year_discontinued": 1988,
        "calc_type": "programmable", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 47,
        "tags": ["programmable", "vintage"],
        "rarity_score": 7.5, "weirdness_score": 5.0,
        "description": "Programmable scientific calculator. Successor to the TI-58/59 series with LCD display instead of LED. Less successful than its predecessors.",
        "images": [],
    },
    {
        "make": "TI", "model": "TI-74 BASICALC",
        "year_introduced": 1985, "year_discontinued": 1990,
        "calc_type": "programmable", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 56,
        "tags": ["programmable", "basic", "vintage"],
        "rarity_score": 7.8, "weirdness_score": 6.0,
        "description": "Pocket computer with BASIC programming language. Could be expanded with ROM modules and a credit-card-size peripherals.",
        "images": [],
    },
    {
        "make": "TI", "model": "TI-74S",
        "year_introduced": 1987, "year_discontinued": 1991,
        "calc_type": "programmable", "display_type": "LCD",
        "power_source": "Battery",
        "tags": ["programmable", "basic", "vintage"],
        "rarity_score": 8.0, "weirdness_score": 6.5,
        "description": "Enhanced TI-74 with improved BASIC interpreter and expanded memory. Rare variant of an already uncommon model.",
        "images": [],
    },
    {
        "make": "TI", "model": "TI-95 PROCALC",
        "year_introduced": 1985, "year_discontinued": 1990,
        "calc_type": "programmable", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 56,
        "tags": ["programmable", "vintage"],
        "rarity_score": 8.2, "weirdness_score": 6.5,
        "description": "TI's high-end programmable from the mid-80s. Could interface with a printer/plotter and magnetic card reader. More capable but less successful than the TI-59.",
        "images": [],
    },
    {
        "make": "TI", "model": "TI-80",
        "year_introduced": 1995, "year_discontinued": 1999,
        "calc_type": "graphing", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 45,
        "tags": ["graphing", "student", "middle-school", "vintage"],
        "rarity_score": 6.0, "weirdness_score": 3.5,
        "description": "Budget graphing calculator for middle school. Simplified interface compared to the TI-82/83. No link port. Often confused with the TI-81.",
        "images": [],
    },
    {
        "make": "TI", "model": "TI-Voyage 200",
        "year_introduced": 2002, "year_discontinued": 2013,
        "calc_type": "graphing", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 75,
        "tags": ["graphing", "cas", "qwerty"],
        "rarity_score": 6.5, "weirdness_score": 7.5,
        "description": "QWERTY graphing CAS calculator — essentially a TI-92 Plus with 2.7× more flash memory and additional Apps. The last of TI's keyboard graphing line.",
        "fun_facts": "The Voyage 200 remained in production for 11 years without any meaningful updates, a testament to its capabilities or TI's confidence that no one would replace it.",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/TI-Voyage_200.jpg/480px-TI-Voyage_200.jpg"],
    },
    {
        "make": "TI", "model": "TI-89 Titanium",
        "year_introduced": 2004,
        "calc_type": "graphing", "display_type": "LCD",
        "power_source": "Battery", "num_keys": 50,
        "tags": ["graphing", "cas", "programmable"],
        "rarity_score": 5.0, "weirdness_score": 4.5,
        "description": "Upgraded TI-89 with 2.7× more flash memory, USB connectivity, and a built-in clock. Titanium faceplate design. Still CAS-capable and still banned from SAT/ACT.",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/TI-89_Titanium_1.jpg/480px-TI-89_Titanium_1.jpg"],
    },
]


async def seed():
    engine_url = DATABASE_URL
    if "asyncpg" not in engine_url:
        engine_url = engine_url.replace("postgresql://", "postgresql+asyncpg://")

    from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
    from sqlalchemy.orm import sessionmaker
    from sqlalchemy import select
    from app.models.calculator import Calculator

    engine = create_async_engine(engine_url)
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    added = skipped = 0
    async with async_session() as session:
        for data in CALCS:
            exists = await session.execute(
                select(Calculator).where(
                    Calculator.make == data["make"],
                    Calculator.model == data["model"],
                )
            )
            if exists.scalar_one_or_none():
                print(f"  skip (exists): {data['make']} {data['model']}")
                skipped += 1
                continue

            calc = Calculator(
                make=data["make"],
                model=data["model"],
                year_introduced=data.get("year_introduced"),
                year_discontinued=data.get("year_discontinued"),
                calc_type=data.get("calc_type", "scientific"),
                display_type=data.get("display_type"),
                power_source=data.get("power_source"),
                num_keys=data.get("num_keys"),
                country_of_origin=data.get("country_of_origin"),
                description=data.get("description"),
                fun_facts=data.get("fun_facts"),
                tags=data.get("tags", []),
                rarity_score=data.get("rarity_score"),
                weirdness_score=data.get("weirdness_score"),
                images=data.get("images", []),
                external_refs=[],
                is_verified=True,
            )
            session.add(calc)
            print(f"  + {data['make']} {data['model']} ({data.get('year_introduced', '?')})")
            added += 1

        await session.commit()

    await engine.dispose()
    print(f"\n✅ Added {added} calculators, skipped {skipped} duplicates")


if __name__ == "__main__":
    asyncio.run(seed())
