"""
CurioCalc — expanded calculator seed
Adds ~90 more calculators across TI, HP, Casio, Sharp, Sinclair, and other key brands.

Run: python scripts/seed_more_calculators.py --api https://api.curiocalc.org
"""
import asyncio, argparse, httpx

CALCULATORS = [

  # ── Texas Instruments — Early LED Era ─────────────────────────────────────
  {"make":"Texas Instruments","model":"TI-2500 Datamath","year_introduced":1972,"calc_type":"other","display_type":"LED","power_source":"9V battery","num_keys":18,"country_of_origin":"USA","description":"The very first Texas Instruments consumer calculator. Named 'Datamath' and sold for $149.95 — equivalent to roughly $1,000 today. Could only do the four basic operations but proved TI could bring mainframe power to your pocket.","fun_facts":"The chip inside the TI-2500 (the TMS0105) was designed in just 6 months. TI went on to dominate the calculator market for decades.","tags":["historic","first","TI","LED","collectible"],"rarity_score":8.5,"weirdness_score":2.0},
  {"make":"Texas Instruments","model":"SR-10","year_introduced":1973,"calc_type":"scientific","display_type":"LED","power_source":"rechargeable","num_keys":18,"country_of_origin":"USA","description":"TI's first scientific calculator — 'SR' stood for Slide Rule. Offered square roots and trigonometric functions, essentially replacing the physical slide rule overnight.","tags":["historic","scientific","LED","TI","SR-series"],"rarity_score":7.5},
  {"make":"Texas Instruments","model":"SR-50","year_introduced":1974,"calc_type":"scientific","display_type":"LED","power_source":"rechargeable","num_keys":40,"country_of_origin":"USA","description":"A full scientific calculator with trig, logs, and exponentials. Considered the first complete 'slide rule replacement' for engineers. Cost $170 at launch.","tags":["scientific","LED","TI","SR-series","engineering"],"rarity_score":7.0},
  {"make":"Texas Instruments","model":"SR-52","year_introduced":1975,"calc_type":"programmable","display_type":"LED","power_source":"rechargeable","num_keys":40,"country_of_origin":"USA","description":"TI's first programmable calculator. Could store up to 224 program steps on magnetic cards — actual magnetic stripe cards you slid through the calculator. Engineers loved it.","fun_facts":"NASA astronauts used the SR-52 on the Apollo-Soyuz mission in 1975, making it the first programmable calculator in space.","tags":["programmable","LED","TI","SR-series","historic","space"],"rarity_score":8.0,"weirdness_score":4.0},
  {"make":"Texas Instruments","model":"SR-56","year_introduced":1976,"calc_type":"programmable","display_type":"LED","power_source":"rechargeable","num_keys":43,"country_of_origin":"USA","description":"A more affordable programmable than the SR-52. 100 program steps, no magnetic cards. Helped bring programmability to the masses.","tags":["programmable","LED","TI","SR-series"],"rarity_score":6.5},
  {"make":"Texas Instruments","model":"TI-55","year_introduced":1977,"calc_type":"scientific","display_type":"LED","power_source":"rechargeable","num_keys":40,"country_of_origin":"USA","description":"TI's workhorse scientific calculator of the late 70s. Had statistics functions and was heavily used in college coursework. Affordable and reliable.","tags":["scientific","LED","TI","student"],"rarity_score":5.0},
  {"make":"Texas Instruments","model":"TI-57","year_introduced":1977,"calc_type":"programmable","display_type":"LED","power_source":"rechargeable","num_keys":40,"country_of_origin":"USA","description":"Budget programmable calculator — 50 program steps. Introduced millions of students to programming. At $79.95, it was the affordable gateway to programmable computing.","tags":["programmable","LED","TI","student","affordable"],"rarity_score":5.5},
  {"make":"Texas Instruments","model":"TI-58","year_introduced":1977,"calc_type":"programmable","display_type":"LED","power_source":"rechargeable","num_keys":40,"country_of_origin":"USA","description":"The TI-58 had 480 program steps and could accept plug-in software modules (called 'solid state software') — little cartridges with pre-written programs for surveying, math, or medicine.","fun_facts":"TI sold dozens of software modules for the 58/59 — a real app store for the late 1970s.","tags":["programmable","LED","TI","modules","historic"],"rarity_score":6.5,"weirdness_score":4.0},
  {"make":"Texas Instruments","model":"TI-59","year_introduced":1977,"calc_type":"programmable","display_type":"LED","power_source":"rechargeable","num_keys":40,"country_of_origin":"USA","description":"The king of TI's programmable LED calculators. 960 program steps, magnetic card reader, plugin software modules, and printer support. A portable computer in 1977.","fun_facts":"The TI-59 user community was so dedicated that Surveying, Medicine, Electrical Engineering and more all had dedicated software libraries — hundreds of programs you could share via magnetic card.","tags":["programmable","LED","TI","professional","historic","flagship"],"rarity_score":7.5,"weirdness_score":3.0},
  {"make":"Texas Instruments","model":"Little Professor","year_introduced":1976,"calc_type":"novelty","display_type":"LED","power_source":"9V battery","num_keys":11,"country_of_origin":"USA","description":"A calculator disguised as a smiling professor that drilled kids on arithmetic. Instead of calculating answers, it GAVE you problems and checked your answers. One of the best-selling educational toys of the 70s.","fun_facts":"The Little Professor was the direct predecessor to the Speak & Math. Over 4 million units were sold in its first decade.","tags":["educational","novelty","LED","TI","toy","kids"],"rarity_score":4.0,"weirdness_score":5.0},
  {"make":"Texas Instruments","model":"DataMan","year_introduced":1977,"calc_type":"novelty","display_type":"LED","power_source":"9V battery","country_of_origin":"USA","description":"A math drill toy that replaced the Little Professor with a sleeker design. Gave kids arithmetic problems and tracked scores. The forerunner of educational gaming.","tags":["educational","novelty","LED","TI","toy","kids"],"rarity_score":4.5,"weirdness_score":3.0},
  {"make":"Texas Instruments","model":"TI-1200","year_introduced":1975,"calc_type":"other","display_type":"LED","power_source":"9V battery","num_keys":18,"country_of_origin":"USA","description":"One of TI's early budget 4-function calculators, priced under $25. Helped make basic calculation affordable for every household. Tiny, cheap, effective.","tags":["basic","LED","TI","budget","4-function"],"rarity_score":3.5},
  {"make":"Texas Instruments","model":"TI-5100","year_introduced":1975,"calc_type":"printing","display_type":"LED","power_source":"AC adapter","country_of_origin":"USA","description":"TI's first printing calculator. Combined an LED display with a built-in thermal paper printer. Used in small offices that wanted a record of calculations without a full adding machine.","tags":["printing","LED","TI","office","thermal"],"rarity_score":6.0},

  # ── Texas Instruments — LCD Graphing Era ──────────────────────────────────
  {"make":"Texas Instruments","model":"TI-81","year_introduced":1990,"calc_type":"graphing","display_type":"LCD","power_source":"4x AA","num_keys":47,"country_of_origin":"Taiwan","description":"The first TI graphing calculator for students. Sparked an entire generation of graphing calc users. Had a 96×64 pixel display and could graph up to 4 functions simultaneously. Changed high school math forever — the TI-84 is its direct descendant.","tags":["graphing","TI","student","historic","first"],"rarity_score":5.0},
  {"make":"Texas Instruments","model":"TI-82","year_introduced":1993,"calc_type":"graphing","display_type":"LCD","power_source":"4x AA","num_keys":47,"country_of_origin":"Taiwan","description":"Added a link port so students could transfer programs between calculators. Had a larger program memory and more built-in statistics than the TI-81. Became a standardized exam tool.","tags":["graphing","TI","student","stats"],"rarity_score":4.0},
  {"make":"Texas Instruments","model":"TI-83","year_introduced":1996,"calc_type":"graphing","display_type":"LCD","power_source":"4x AAA","num_keys":46,"country_of_origin":"China","description":"The calculator that basically defined American standardized testing for a generation. The TI-83/84 family is the most widely used graphing calculator series in history.","tags":["graphing","TI","iconic","student","standardized-tests"],"rarity_score":2.0},
  {"make":"Texas Instruments","model":"TI-83 Plus","year_introduced":1999,"calc_type":"graphing","display_type":"LCD","power_source":"4x AAA","num_keys":46,"country_of_origin":"China","description":"Added Flash ROM for software updates and downloadable apps — a revolution at the time. The first calculator where you could download new programs from the internet (via your computer). Spawned an enormous homebrew community.","tags":["graphing","TI","iconic","student","flash","apps"],"rarity_score":2.0},
  {"make":"Texas Instruments","model":"TI-84 Plus Silver Edition","year_introduced":2004,"calc_type":"graphing","display_type":"LCD","power_source":"4x AAA + lithium backup","num_keys":42,"country_of_origin":"China","description":"More memory than the base TI-84 Plus and came in translucent colors. Popular with students who wanted to stand out. Had a USB port for computer connectivity.","tags":["graphing","TI","student","silver"],"rarity_score":2.5},
  {"make":"Texas Instruments","model":"TI-84 Plus CE","year_introduced":2015,"calc_type":"graphing","display_type":"color LCD","power_source":"lithium rechargeable","num_keys":42,"country_of_origin":"China","description":"The modern TI-84 — thinner, lighter, with a color screen and rechargeable battery. Still uses essentially the same processor as the 1993 TI-82. The operating system is modern; the hardware soul is ancient.","fun_facts":"The TI-84 CE runs on a Z80-based processor at 48 MHz — the same architecture as the TI-82 from 1993, just clocked faster. A 2015 calculator with 1993 architecture.","tags":["graphing","TI","color","modern","student"],"rarity_score":1.5},
  {"make":"Texas Instruments","model":"TI-85","year_introduced":1992,"calc_type":"graphing","display_type":"LCD","power_source":"4x AA","num_keys":48,"country_of_origin":"USA","description":"Designed for engineering students — more powerful than the TI-81/82 with more memory and complex number support. Had a matrix editor that made linear algebra courses much more bearable.","tags":["graphing","TI","engineering","student"],"rarity_score":4.0},
  {"make":"Texas Instruments","model":"TI-86","year_introduced":1997,"calc_type":"graphing","display_type":"LCD","power_source":"4x AA","num_keys":50,"country_of_origin":"China","description":"The successor to the TI-85, targeted at engineering and physics students. Had a larger screen and more memory. Cult following among engineering majors who needed more than the TI-84.","tags":["graphing","TI","engineering","student","cult-classic"],"rarity_score":4.5},
  {"make":"Texas Instruments","model":"TI-89","year_introduced":1998,"calc_type":"graphing","display_type":"LCD","power_source":"4x AAA","num_keys":63,"country_of_origin":"China","description":"The TI-89 had a full CAS (Computer Algebra System) — it could solve calculus problems symbolically. Banned from some exams but beloved by engineers. Running Motorola 68000 processor at 10MHz made it feel like a minicomputer.","fun_facts":"The TI-89 runs the same processor family as the original Macintosh. Hardcore users ran programming environments, wrote games, and even emulated other calculators on it.","tags":["graphing","CAS","TI","engineering","powerful","cult-classic"],"rarity_score":4.0,"weirdness_score":3.0},
  {"make":"Texas Instruments","model":"TI-89 Titanium","year_introduced":2004,"calc_type":"graphing","display_type":"LCD","power_source":"4x AAA","num_keys":63,"country_of_origin":"China","description":"Updated TI-89 with more memory, a USB port, and a sleeker design. Still the go-to CAS calculator for college engineering/math majors. Banned from most exams but allowed on the AP Calculus exam.","tags":["graphing","CAS","TI","engineering","powerful"],"rarity_score":3.5},
  {"make":"Texas Instruments","model":"TI-92","year_introduced":1995,"calc_type":"graphing","display_type":"LCD","power_source":"4x AA","num_keys":85,"country_of_origin":"China","description":"A full QWERTY keyboard calculator with CAS. The size of a paperback book — too big for most exam policies. Had a built-in geometry application that could dynamically construct geometric figures.","fun_facts":"The TI-92 was banned from virtually every standardized exam because it was considered too powerful. TI had to release a stripped-down version (TI-92 Plus) to address the controversy.","tags":["graphing","CAS","TI","QWERTY","banned","large"],"rarity_score":5.5,"weirdness_score":5.0},
  {"make":"Texas Instruments","model":"Voyage 200","year_introduced":2002,"calc_type":"graphing","display_type":"LCD","power_source":"4x AA","num_keys":85,"country_of_origin":"China","description":"The successor to the TI-92 Plus. Full QWERTY, CAS, large screen. Essentially a dedicated math computer. Banned from almost all exams. Still beloved by power users and math competition teams.","tags":["graphing","CAS","TI","QWERTY","powerful","rare"],"rarity_score":6.0,"weirdness_score":4.0},
  {"make":"Texas Instruments","model":"TI-Nspire CX II","year_introduced":2019,"calc_type":"graphing","display_type":"color LCD","power_source":"lithium rechargeable","num_keys":85,"country_of_origin":"China","description":"The latest generation TI-Nspire — faster, thinner, full-color, rechargeable. The most capable standardized-test-legal calculator TI makes.","tags":["graphing","color","TI","modern"]},

  # ── Texas Instruments — Scientific / Financial ────────────────────────────
  {"make":"Texas Instruments","model":"TI-30Xa","year_introduced":1994,"calc_type":"scientific","display_type":"LCD","power_source":"solar+battery","num_keys":31,"country_of_origin":"China","description":"The reliable workhorse of high school science classrooms everywhere. Solar-powered, virtually indestructible, and sold for under $10. Billions sold. If you took chemistry in school, you've used one.","tags":["scientific","TI","school","solar","ubiquitous","student"],"rarity_score":1.0},
  {"make":"Texas Instruments","model":"TI-30X IIS","year_introduced":1998,"calc_type":"scientific","display_type":"LCD","power_source":"solar+battery","num_keys":40,"country_of_origin":"China","description":"Two-line display scientific calculator. The first non-graphing TI with scrollable history — you could scroll back through previous calculations. Huge quality-of-life improvement for students.","tags":["scientific","TI","school","two-line","student"],"rarity_score":1.5},
  {"make":"Texas Instruments","model":"TI-36X Pro","year_introduced":2011,"calc_type":"scientific","display_type":"LCD","power_source":"solar+battery","num_keys":50,"country_of_origin":"China","description":"The most powerful non-graphing scientific calculator allowed on engineering exams (FE, PE exams). Can do unit conversions, numeric differentiation/integration, matrix operations, and complex numbers. A graphing calc without the graph.","tags":["scientific","TI","engineering","exams","FE-exam","powerful"],"rarity_score":2.5},
  {"make":"Texas Instruments","model":"BA II Plus","year_introduced":1991,"calc_type":"financial","display_type":"LCD","power_source":"battery","num_keys":34,"country_of_origin":"China","description":"The standard calculator for the CFA exam and most finance courses. Does TVM (time value of money), bond pricing, NPV, IRR, and depreciation. Not exciting, but a career tool for finance professionals.","tags":["financial","TI","CFA","professional","finance"],"rarity_score":2.0},
  {"make":"Texas Instruments","model":"BA II Plus Professional","year_introduced":2004,"calc_type":"financial","display_type":"LCD","power_source":"battery","num_keys":34,"country_of_origin":"China","description":"Premium version of the BA II Plus with more memory and additional functions. The CFA exam allows both; the Professional model is faster and has more worksheet functionality.","tags":["financial","TI","CFA","professional","finance"],"rarity_score":2.5},
  {"make":"Texas Instruments","model":"TI-108","year_introduced":1990,"calc_type":"other","display_type":"LCD","power_source":"solar","num_keys":19,"country_of_origin":"China","description":"The cheapest, most basic calculator TI makes. 4 functions, solar power, no batteries needed, virtually indestructible. Given to elementary school students by the millions. Ubiquitous in every American classroom.","tags":["basic","TI","school","solar","elementary","cheap"],"rarity_score":1.0},
  {"make":"Texas Instruments","model":"TI-Nspire CX CAS","year_introduced":2011,"calc_type":"graphing","display_type":"color LCD","power_source":"lithium rechargeable","num_keys":85,"country_of_origin":"China","description":"TI's flagship CAS graphing calculator. Full color screen, Computer Algebra System, rechargeable. Can do symbolic calculus, 3D graphing, and run Python programs. Essentially a dedicated math computer.","tags":["graphing","CAS","TI","color","powerful"],"rarity_score":3.0},

  # ── Hewlett-Packard — The RPN Dynasty ──────────────────────────────────────
  {"make":"Hewlett-Packard","model":"HP-45","year_introduced":1973,"calc_type":"scientific","display_type":"LED","power_source":"rechargeable","num_keys":35,"country_of_origin":"USA","description":"HP's second scientific calculator and the first with a truly complete scientific function set. Popular with engineers for its RPN entry and 4-level stack. Vastly more capable than anything else in 1973.","tags":["scientific","RPN","HP","LED","historic","engineering"],"rarity_score":7.0},
  {"make":"Hewlett-Packard","model":"HP-65","year_introduced":1974,"calc_type":"programmable","display_type":"LED","power_source":"rechargeable","num_keys":35,"country_of_origin":"USA","description":"The world's first handheld programmable scientific calculator. Used magnetic program cards. Cost $795 at launch. NASA used it as a backup computer on the Apollo-Soyuz mission.","fun_facts":"HP-65 users formed the HP-65 Users Club, one of the first communities built around a calculator. They shared magnetic cards by mail.","tags":["programmable","LED","HP","historic","first","space","rare","collectible"],"rarity_score":9.0,"weirdness_score":3.0},
  {"make":"Hewlett-Packard","model":"HP-67","year_introduced":1976,"calc_type":"programmable","display_type":"LED","power_source":"rechargeable","num_keys":35,"country_of_origin":"USA","description":"226 program steps, magnetic card reader, and continuous memory. The pinnacle of HP's LED programmable era. Used by engineers and scientists who needed serious portable computing power.","tags":["programmable","LED","HP","historic","professional","rare"],"rarity_score":8.0},
  {"make":"Hewlett-Packard","model":"HP-80","year_introduced":1973,"calc_type":"financial","display_type":"LED","power_source":"rechargeable","num_keys":35,"country_of_origin":"USA","description":"The world's first financial pocket calculator. Could do compound interest, TVM, and bond calculations. Before this, bankers used paper tables. After this, they used HP.","tags":["financial","LED","HP","historic","first","banking"],"rarity_score":8.5},
  {"make":"Hewlett-Packard","model":"HP-25","year_introduced":1975,"calc_type":"programmable","display_type":"LED","power_source":"rechargeable","num_keys":32,"country_of_origin":"USA","description":"49-step programmable at an affordable $195 price point. Brought programmability to engineers who couldn't justify the HP-65. Beloved for its clean design and solid RPN implementation.","tags":["programmable","LED","HP","RPN","engineering"],"rarity_score":7.0},
  {"make":"Hewlett-Packard","model":"HP-41C","year_introduced":1979,"calc_type":"programmable","display_type":"LCD","power_source":"4x N","num_keys":44,"country_of_origin":"USA","description":"HP's most expandable calculator ever. Could accept modules (math, surveying, medicine, games), had a card reader port, and printer port. The first HP with alphanumeric display. Survey crews used it for decades.","fun_facts":"The HP-41C had an accessory called the 'Quad Memory Module' — just more RAM. HP also made a barcode reader wand that could scan programs printed in newspapers.","tags":["programmable","RPN","HP","expandable","modules","historic","iconic"],"rarity_score":6.5,"weirdness_score":4.0},
  {"make":"Hewlett-Packard","model":"HP-41CX","year_introduced":1983,"calc_type":"programmable","display_type":"LCD","power_source":"4x N","num_keys":44,"country_of_origin":"USA","description":"The ultimate HP-41 — all the features of the 41C with extra memory and a built-in time module. Used by oil field engineers, pilots, and surveyors well into the 2000s. NASA flew one to Skylab.","tags":["programmable","RPN","HP","professional","space","iconic"],"rarity_score":7.0},
  {"make":"Hewlett-Packard","model":"HP-11C","year_introduced":1981,"calc_type":"scientific","display_type":"LCD","power_source":"3x LR44","num_keys":35,"country_of_origin":"USA","description":"The Voyager series slim scientific. Continuous memory, hyperbolic functions, complex number mode. One of the most elegant calculator designs HP ever made. Thin as a credit card (almost).","tags":["scientific","RPN","HP","voyager","slim","elegant"],"rarity_score":5.5},
  {"make":"Hewlett-Packard","model":"HP-15C","year_introduced":1982,"calc_type":"scientific","display_type":"LCD","power_source":"3x LR44","num_keys":35,"country_of_origin":"USA","description":"The most beloved scientific calculator HP ever made. Matrix operations, complex numbers, numeric integration, root-finding — all in a shirt-pocket calculator. Still fetches $100+ on eBay. HP reissued it in 2023 due to demand.","fun_facts":"The HP-15C Collector's Edition (2023 reissue) sold out within days. The original still holds a passionate community 40+ years later.","tags":["scientific","RPN","HP","voyager","beloved","cult-classic","collectible","still-coveted"],"rarity_score":6.0,"weirdness_score":2.0},
  {"make":"Hewlett-Packard","model":"HP-16C","year_introduced":1982,"calc_type":"scientific","display_type":"LCD","power_source":"3x LR44","num_keys":35,"country_of_origin":"USA","description":"The programmer's calculator. Binary, octal, hex, and decimal modes. Bit manipulation, shifts, rotates, flag operations. Designed for computer programmers and still used by embedded engineers today.","fun_facts":"HP-16C owners include generations of hardware engineers and embedded programmers. There's a thriving community of people writing HP-16C emulators and clones.","tags":["scientific","RPN","HP","voyager","programming","hex","embedded","cult-classic"],"rarity_score":6.5,"weirdness_score":3.0},
  {"make":"Hewlett-Packard","model":"HP-42S","year_introduced":1988,"calc_type":"scientific","display_type":"LCD","power_source":"3x LR44","num_keys":37,"country_of_origin":"USA","description":"Many consider the HP-42S the pinnacle of HP scientific calculators — RPN with a 2-line alphanumeric display, equation solver, matrix math, complex numbers. More capable than the beloved HP-15C in a similar size.","fun_facts":"The HP-42S community built 'Free42' — a perfect emulator that runs on every platform — because real units are so hard to find. New units sell for $200-300.","tags":["scientific","RPN","HP","professional","cult-classic","collectible"],"rarity_score":7.0,"weirdness_score":2.0},
  {"make":"Hewlett-Packard","model":"HP-17BII","year_introduced":1990,"calc_type":"financial","display_type":"LCD","power_source":"2x CR2032","num_keys":35,"country_of_origin":"Singapore","description":"HP's premium financial calculator — menu-driven, equation solver, TVM, statistics. A real competitor to the HP-12C for business users who prefer algebraic entry. Popular on the CFA exam.","tags":["financial","HP","business","CFA"],"rarity_score":4.0},
  {"make":"Hewlett-Packard","model":"HP-49G","year_introduced":1999,"calc_type":"graphing","display_type":"LCD","power_source":"3x AAA","num_keys":50,"country_of_origin":"China","description":"HP's graphing CAS calculator — meant to compete with the TI-89. Ran RPL (a Forth-based programming language). Had an SD card slot. A bit rough around the edges but beloved by HP loyalists.","tags":["graphing","CAS","RPN","RPL","HP","engineering"],"rarity_score":5.0},
  {"make":"Hewlett-Packard","model":"HP-50G","year_introduced":2006,"calc_type":"graphing","display_type":"LCD","power_source":"3x AAA","num_keys":50,"country_of_origin":"China","description":"The last of HP's RPN graphing calculators. More memory than the HP-49G, SD card slot, faster CPU. Used by engineers and scientists who refused to switch to TI. Discontinued in 2015.","tags":["graphing","CAS","RPN","RPL","HP","engineering","last-of-kind"],"rarity_score":5.5},
  {"make":"Hewlett-Packard","model":"HP Prime","year_introduced":2013,"calc_type":"graphing","display_type":"color LCD","power_source":"lithium rechargeable","num_keys":50,"country_of_origin":"China","description":"HP's modern graphing calculator — touchscreen, full color, CAS, rechargeable. Runs ARM processor at 400MHz. The most powerful calculator HP has made. Supports RPN, algebraic, and textbook entry.","tags":["graphing","CAS","touchscreen","color","modern","HP","powerful"],"rarity_score":3.5},

  # ── Casio — The Scientific Powerhouse ──────────────────────────────────────
  {"make":"Casio","model":"14-A","year_introduced":1957,"calc_type":"other","display_type":"relay","power_source":"AC adapter","country_of_origin":"Japan","description":"The very first Casio product — an electromechanical relay calculator. Used 342 relays and 10 memory circuits. Weighed 140kg and sat on a desk. Could multiply 2 numbers in a single step — revolutionary for 1957.","fun_facts":"The 14-A was invented by Toshio Kashio in his brother's garage workshop using WWII surplus parts. It launched the Casio empire.","tags":["historic","first","Casio","relay","electromechanical","heavy","rare"],"rarity_score":10.0,"weirdness_score":6.0},
  {"make":"Casio","model":"Casio Mini","year_introduced":1972,"calc_type":"other","display_type":"LED","power_source":"AC adapter","country_of_origin":"Japan","description":"The calculator that brought basic arithmetic to Japanese households. At ¥12,800 (a breakthrough low price), the Casio Mini sold over 1 million units in its first year. Launched the era of affordable mass-market calculators.","tags":["historic","first","Casio","LED","affordable","Japan","mass-market"],"rarity_score":7.5},
  {"make":"Casio","model":"fx-1","year_introduced":1972,"calc_type":"scientific","display_type":"LED","power_source":"AC adapter","country_of_origin":"Japan","description":"Casio's first scientific calculator. Competed directly with the HP-35 but at a lower price point. Helped establish Casio as a serious competitor in the scientific calculator market.","tags":["historic","scientific","Casio","LED","first"],"rarity_score":8.0},
  {"make":"Casio","model":"fx-82","year_introduced":1981,"calc_type":"scientific","display_type":"LCD","power_source":"solar+battery","num_keys":38,"country_of_origin":"Japan","description":"The calculator for students worldwide — especially outside the USA. In Europe, Asia, Australia, and Africa, the fx-82 series is the standard school calculator. Updated every few years with natural display, more functions, etc.","tags":["scientific","Casio","school","international","ubiquitous","student"],"rarity_score":1.0},
  {"make":"Casio","model":"fx-991EX Classwiz","year_introduced":2015,"calc_type":"scientific","display_type":"LCD","power_source":"solar+battery","num_keys":54,"country_of_origin":"Japan","description":"The current flagship scientific Casio — high-resolution display that shows natural math notation, QR code output to your phone, spreadsheet mode, and equation solving. 552 functions. The most capable non-graphing calculator widely available.","fun_facts":"The fx-991EX generates QR codes that open on your phone to show graphs of calculations you entered on the calculator. It has more features than most graphing calculators from the 1990s.","tags":["scientific","Casio","modern","powerful","QR","student","international"],"rarity_score":1.5,"weirdness_score":3.0},
  {"make":"Casio","model":"fx-570ES PLUS","year_introduced":2010,"calc_type":"scientific","display_type":"LCD","power_source":"solar+battery","num_keys":46,"country_of_origin":"Japan","description":"Natural-display scientific with 'Natural Textbook Display' — fractions look like fractions, roots look like roots. The global standard school calculator for over a decade.","tags":["scientific","Casio","student","school","natural-display","international"],"rarity_score":1.5},
  {"make":"Casio","model":"fx-9750GII","year_introduced":2010,"calc_type":"graphing","display_type":"LCD","power_source":"4x AA","num_keys":79,"country_of_origin":"Japan","description":"Casio's budget graphing calculator. Still does everything the pricier models do — graphing, stats, matrices — but at a much lower price. Popular in Australia and New Zealand where it's a standard exam calculator.","tags":["graphing","Casio","budget","student","Australia"],"rarity_score":2.5},
  {"make":"Casio","model":"fx-9860GII","year_introduced":2010,"calc_type":"graphing","display_type":"LCD","power_source":"4x AA","num_keys":80,"country_of_origin":"Japan","description":"Casio's mid-range graphing calculator. Faster CPU than the 9750, more built-in functions. Can run add-in applications. Popular in Europe as an exam-legal alternative to the TI-84.","tags":["graphing","Casio","student","Europe","exam"],"rarity_score":3.0},
  {"make":"Casio","model":"ClassPad 330","year_introduced":2006,"calc_type":"graphing","display_type":"color LCD","power_source":"4x AA","country_of_origin":"Japan","description":"A graphing calculator with a touchscreen and stylus. CAS, full color, drag-and-drop interface. Wildly ahead of its time in 2006. Still doesn't look particularly modern even now.","fun_facts":"The ClassPad could run an animated 3D globe as a screensaver — this was a _calculator_ in 2006.","tags":["graphing","CAS","touchscreen","Casio","unusual","ahead-of-time"],"rarity_score":5.0,"weirdness_score":6.0},
  {"make":"Casio","model":"CM-100","year_introduced":1974,"calc_type":"other","display_type":"LED","power_source":"battery","country_of_origin":"Japan","description":"An early Casio scientific that was notable for fitting into a shirt pocket. In 1974, a shirt-pocket scientific calculator was a minor miracle.","tags":["scientific","Casio","LED","pocket","historic"],"rarity_score":7.5},

  # ── Sharp ────────────────────────────────────────────────────────────────────
  {"make":"Sharp","model":"EL-5100","year_introduced":1978,"calc_type":"programmable","display_type":"LCD","power_source":"battery","country_of_origin":"Japan","description":"One of the first programmable LCD calculators. Sharp's answer to TI's and HP's programmable machines, in a much smaller form factor.","tags":["programmable","Sharp","LCD","historic"],"rarity_score":6.5},
  {"make":"Sharp","model":"PC-1211","year_introduced":1980,"calc_type":"programmable","display_type":"LCD","power_source":"4x LR44","country_of_origin":"Japan","description":"The world's first pocket computer. Ran BASIC, had 1424 bytes of RAM, and could be connected to a printer/cassette interface. Smaller than a VHS tape. Sold as the TRS-80 Pocket Computer in the USA.","fun_facts":"The PC-1211 is considered the world's first pocket computer. It ran a dialect of BASIC and could store and run programs — a genuine computer in your shirt pocket.","tags":["programmable","Sharp","LCD","pocket-computer","BASIC","historic","first"],"rarity_score":8.0,"weirdness_score":6.0},
  {"make":"Sharp","model":"EL-9300","year_introduced":1992,"calc_type":"graphing","display_type":"LCD","power_source":"2x CR2032","country_of_origin":"Japan","description":"Sharp's graphing calculator. Smaller and thinner than the TI-82, with a clamshell case to protect the screen. Never achieved TI's market dominance but had devoted users.","tags":["graphing","Sharp","clamshell","student"],"rarity_score":5.0},
  {"make":"Sharp","model":"EL-W516","year_introduced":2010,"calc_type":"scientific","display_type":"LCD","power_source":"solar+battery","num_keys":56,"country_of_origin":"China","description":"Sharp's flagship scientific with WriteView display — shows equations in natural textbook format. 556 functions, equation solver, direct algebraic logic. Under-appreciated but genuinely excellent.","tags":["scientific","Sharp","natural-display","WriteView"],"rarity_score":3.0},

  # ── Sinclair — British Ingenuity ─────────────────────────────────────────────
  {"make":"Sinclair","model":"Scientific","year_introduced":1975,"calc_type":"scientific","display_type":"LED","power_source":"9V battery","country_of_origin":"UK","description":"Clive Sinclair's proper scientific calculator. More reliable than the Cambridge and included better math functions. Still had the quirky Sinclair approach of doing more with less silicon than anyone thought possible.","tags":["scientific","Sinclair","UK","LED","budget"],"rarity_score":7.5},
  {"make":"Sinclair","model":"Programmable","year_introduced":1975,"calc_type":"programmable","display_type":"LED","power_source":"9V battery","country_of_origin":"UK","description":"24 program steps for £25 — Sinclair made programmable calculators accessible to ordinary people. Primitive by HP/TI standards but an incredible achievement for the price.","tags":["programmable","Sinclair","UK","LED","budget","historic"],"rarity_score":8.0},

  # ── Commodore ────────────────────────────────────────────────────────────────
  {"make":"Commodore","model":"SR-4148R","year_introduced":1977,"calc_type":"scientific","display_type":"LED","power_source":"rechargeable","country_of_origin":"USA","description":"Commodore (yes, the computer company) made calculators before the PET and C64. This one used RPN and competed directly with HP's scientific line at a lower price.","fun_facts":"Jack Tramiel's Commodore Business Machines got its start making calculators before pivoting to home computers. The calculator business trained the team that built the C64.","tags":["scientific","RPN","Commodore","LED","historic","pre-computer"],"rarity_score":7.0,"weirdness_score":4.0},
  {"make":"Commodore","model":"PR-100","year_introduced":1977,"calc_type":"programmable","display_type":"LED","power_source":"rechargeable","country_of_origin":"USA","description":"Commodore's programmable calculator — 72 program steps, RPN. Never achieved the reputation of HP's programmables but was significantly cheaper. Interesting as a pre-computer Commodore artifact.","tags":["programmable","RPN","Commodore","LED","historic"],"rarity_score":7.5},

  # ── Historic / Pioneering ────────────────────────────────────────────────────
  {"make":"Canon","model":"Pocketronic","year_introduced":1970,"calc_type":"printing","display_type":"thermal paper","power_source":"rechargeable","country_of_origin":"Japan","description":"The world's first truly portable electronic calculator. Used thermal paper instead of a display (no room for one). Required a handbag to carry — 'pocket' was aspirational. Based on a cancelled TI research project.","fun_facts":"The Pocketronic was based on the 'Cal-Tech' prototype that Jack Kilby's team at TI built in 1967. TI licensed the patent to Canon rather than produce it themselves.","tags":["historic","first","printing","Canon","thermal","portable","milestone"],"rarity_score":9.5,"weirdness_score":5.0},
  {"make":"Busicom","model":"141-PF","year_introduced":1971,"calc_type":"printing","display_type":"nixie tube","power_source":"AC adapter","country_of_origin":"Japan","description":"This calculator is historically significant because it was the first product to use the Intel 4004 — the world's first commercial microprocessor. Intel designed the 4004 specifically for this Busicom calculator.","fun_facts":"The Intel 4004 chip that powers the Busicom 141-PF started the entire microprocessor revolution. Intel later bought back the full rights to use the design in other products.","tags":["historic","nixie","Intel-4004","microprocessor","first","Busicom","milestone"],"rarity_score":10.0,"weirdness_score":5.0},
  {"make":"ANITA","model":"Mk VII","year_introduced":1961,"calc_type":"other","display_type":"nixie tube","power_source":"AC adapter","country_of_origin":"UK","description":"ANITA (A New Inspiration To Arithmetic) — the world's first fully electronic desktop calculator. Used vacuum tubes and nixie tube displays. Performed all four functions and was manufactured by Bell Punch Company in Britain.","fun_facts":"Before the ANITA Mk VII, all calculators were mechanical or electromechanical. The ANITA replaced moving gears with vacuum tubes. It cost £355 — nearly a year's salary for many workers.","tags":["historic","first","nixie","vacuum-tube","UK","electromechanical","milestone"],"rarity_score":10.0,"weirdness_score":7.0},
  {"make":"Curta","model":"Type I","year_introduced":1948,"calc_type":"other","display_type":"mechanical","power_source":"none","country_of_origin":"Liechtenstein","description":"A hand-cranked mechanical calculator the size of a pepper grinder. 11-digit capacity. Invented by Curt Herzstark while a prisoner in the Nazi concentration camp Buchenwald — he designed it entirely from memory as a 'gift for the Führer.' After liberation, he built it in Liechtenstein.","fun_facts":"Herzstark invented the Curta to give to Hitler as a 'gift' in hopes of better treatment. After liberation he found investors in Liechtenstein and it became a beloved instrument for rally car navigation for decades.","tags":["historic","mechanical","Curta","rare","collectible","WW2","hand-cranked","Liechtenstein"],"rarity_score":9.5,"weirdness_score":8.0},
  {"make":"Olivetti","model":"Programma 101","year_introduced":1965,"calc_type":"programmable","display_type":"printer","power_source":"AC adapter","country_of_origin":"Italy","description":"Considered by many the first commercially sold programmable computer small enough for a desk (as opposed to a room). NASA bought 10 of them to help calculate trajectories for the Apollo 11 Moon landing. Cost $3,200.","fun_facts":"NASA used 10 Programma 101s to calculate and verify the trajectory for Apollo 11's Moon landing. HP later paid Olivetti $900,000 in a patent settlement because the HP-9100A too closely resembled it.","tags":["historic","programmable","Olivetti","Italy","NASA","Apollo","milestone","desktop"],"rarity_score":9.5,"weirdness_score":4.0},
  {"make":"Friden","model":"EC-130","year_introduced":1964,"calc_type":"other","display_type":"CRT","power_source":"AC adapter","country_of_origin":"USA","description":"The first calculator with a CRT (cathode ray tube) display. Used 4 columns of numbers on the screen instead of mechanical registers. Weighed 55 pounds. Cost $2,100 in 1964. Remarkable for showing calculation results on a tiny screen.","tags":["historic","CRT","desktop","rare","collectible","Friden","heavy"],"rarity_score":9.0,"weirdness_score":6.0},

  # ── Modern Curiosities ────────────────────────────────────────────────────────
  {"make":"NumWorks","model":"N0110","year_introduced":2017,"calc_type":"graphing","display_type":"color LCD","power_source":"lithium rechargeable","num_keys":45,"country_of_origin":"France","description":"A modern open-source graphing calculator with a beautiful color display, Python programming, and an OS you can read and modify on GitHub. The first truly open-source mainstream graphing calculator. Refreshing in a market TI has dominated for 30 years.","fun_facts":"NumWorks ships the complete source code of their OS on GitHub. Users have submitted pull requests to fix bugs and add features. A calculator where you can fix the math yourself.","tags":["graphing","modern","open-source","Python","France","color","NumWorks","innovative"],"rarity_score":3.0,"weirdness_score":4.0},
  {"make":"SwissMicros","model":"DM42","year_introduced":2017,"calc_type":"scientific","display_type":"LCD","power_source":"CR2032","country_of_origin":"Switzerland","description":"A metal-cased recreation of the HP-42S, running a perfect HP-42S emulator (Free42) on modern hardware. 128MB RAM, USB, and a sharp e-paper-like screen. Made for HP RPN enthusiasts who want the HP-42S experience in a new body.","fun_facts":"The DM42 runs Free42 — an open-source HP-42S emulator. It has more RAM than the original HP-42S could ever address, so memory limitations are completely gone.","tags":["scientific","RPN","HP-compatible","Swiss","metal","modern","premium","HP-42S"],"rarity_score":5.0,"weirdness_score":3.0},
  {"make":"Casio","model":"fx-CG500","year_introduced":2017,"calc_type":"graphing","display_type":"color LCD","power_source":"4x AA","num_keys":62,"country_of_origin":"Japan","description":"A graphing calculator with a touchscreen AND physical keys — the best of both worlds. CAS, 3D graphing, Python programming. Allowed in exams in some countries. Casio's attempt to modernize without abandoning the tactile keyboard.","tags":["graphing","CAS","touchscreen","color","Casio","modern"],"rarity_score":4.0,"weirdness_score":3.0},
  {"make":"Hewlett-Packard","model":"HP-35S","year_introduced":2007,"calc_type":"scientific","display_type":"LCD","power_source":"2x CR2032","num_keys":43,"country_of_origin":"China","description":"HP's 35th anniversary calculator — a remake of the HP-35 for the modern era. Supports both RPN and algebraic entry, two-line display, and is permitted on engineering exams (FE/PE). One of the few modern HP calculators that feels like an HP calculator.","tags":["scientific","RPN","HP","engineering","FE-exam","anniversary"],"rarity_score":3.0},
]

async def seed(api_url: str, token: str):
    async with httpx.AsyncClient(timeout=30, base_url=api_url) as client:
        headers = {"Authorization": f"Bearer {token}"}
        ok, skip, fail = 0, 0, 0

        # Get existing models to avoid duplicates
        r = await client.get("/api/v1/calculators?limit=500")
        existing = {(c["make"], c["model"]) for c in r.json()}
        print(f"  {len(existing)} existing calculators in DB\n")

        for c in CALCULATORS:
            key = (c["make"], c["model"])
            if key in existing:
                print(f"  ⏭   {c['make']} {c['model']} — already exists")
                skip += 1
                continue
            r = await client.post("/api/v1/calculators", json=c, headers=headers)
            if r.status_code == 201:
                print(f"  ✅  {c['make']} {c['model']}")
                ok += 1
            else:
                print(f"  ❌  {c['make']} {c['model']} — {r.status_code} {r.text[:60]}")
                fail += 1

        print(f"\n{ok} added, {skip} skipped (already exist), {fail} failed")

async def main():
    p = argparse.ArgumentParser()
    p.add_argument("--api",      default="https://api.curiocalc.org")
    p.add_argument("--email",    default="admin@curiocalc.org")
    p.add_argument("--password", default="changeme123")
    args = p.parse_args()

    async with httpx.AsyncClient(timeout=15, base_url=args.api) as client:
        r = await client.post("/api/v1/auth/login",
            data={"username": args.email, "password": args.password},
            headers={"Content-Type": "application/x-www-form-urlencoded"})
        if r.status_code != 200:
            print(f"Login failed: {r.text}"); return
        token = r.json()["access_token"]
        print(f"Logged in ✅  Seeding {len(CALCULATORS)} calculators…\n")

    await seed(args.api, token)

if __name__ == "__main__":
    asyncio.run(main())
